Updated the name lists!
ClanGenOfficial/clangen pull request #1064
Opened 2023-03-21 23:06 UTC by hobohime

I took out some duplicate names and kept others as some of them are canon names and we keep cannon names in the normal pool until someone decides differently.

Didn't touch the names for wetlands and desert bc they're not implemented yet, there is no reason to limit names that cannot be gotten in game yet.

2023-03-21 23:42 UTC, capillarys commented
psst i thought duplicates were meant to make a name more common? or do you think those names weren't meant to be common (just out of curiosity)

2023-03-22 15:36 UTC, lillithrosepup commented
> psst i thought duplicates were meant to make a name more common? or do you think those names weren't meant to be common (just out of curiosity)

It does make it more common, but i asked ryos a bit ago and they are p sure its an accident that the lines were duped.

2023-03-22 16:16 UTC, Ryos00 requested changes

2023-03-22 16:16 UTC, Ryos00 commented on resources/dicts/names/names.json
> -    "Big", "Birch", "Bird", "Bite", "Bitter", "Bittern", "Blizzard", "Bloom", "Bud",
I'd probably leave "Birch" in here since it's canon and used multiple times

2023-03-22 16:19 UTC, Ryos00 approved these changes

2023-03-22 16:19 UTC, merged

2023-03-22 21:35 UTC, capillarys commented
ahhh big excite ty hobo for names-ing and ty ryos for ze merge!! i shall now try to get some drunkelskogs in