added more war events
ClanGenOfficial/clangen pull request #1394
Opened 2023-04-22 21:22 UTC by dusk0220

pls don't merge yet!! wip :)

2023-05-04 17:31 UTC, scribblecrumb requested changes
Looks great!  Just a few little fixes and missing pronoun tags.  I'd also love to see some of these death events have corresponding injury events where the cat survives, but with injuries!  But, that of course can be a different PR.

2023-05-04 17:31 UTC, scribblecrumb commented on resources/dicts/events/death/general/general.json
> +        "death_text": "m_c sacrificed themself for r_c in a battle with o_c.",
missing a pronoun tag for "themself", double check pronoun tags for all your additions please!

2023-05-04 17:31 UTC, scribblecrumb commented on resources/dicts/events/misc_events/general/mediator.json
> +        "tags": ["Newleaf", "Greenleaf", "Leaf-fall", "Leaf-bare", "war", "other_cat_leader" ],
make sure to add the "other_cat" as well!  the more specific "other_cat_leader" tags will not work without it

2023-05-04 17:31 UTC, scribblecrumb commented on resources/dicts/events/new_cat/general/general.json
> +        "backstory": ["otherclan2", "disgraced", "refugee1", "tragedy_survivir1", "otherclan2"],
mispelled tragedy_survivor

2023-05-05 15:49 UTC, scribblecrumb requested changes
missed some VERB tags! make sure to double check the verbs by reading the sentence with both they/them and she/her or he/him pronouns in order to check that plural/singular verbs are correctly tagged.

2023-05-05 15:49 UTC, scribblecrumb commented on resources/dicts/events/death/general/general.json
> +        "death_text": "m_c sacrificed {PRONOUN/m_c/self} by taking on the role of a messenger, delivering important information that could save {PRONOUN/m_c/poss} Clan. {PRONOUN/m_c/subject} were kil
"were" in the last sentence needs to be a VERB tag

2023-05-05 15:49 UTC, scribblecrumb commented on resources/dicts/events/new_cat/general/general.json
> +        "event_text": "A member of o_c defects in the war and chooses to join c_n. {PRONOUN/m_c/subject} have decided to keep {PRONOUN/m_c/poss} name.",
"have" needs to be a VERB tag

2023-05-05 15:49 UTC, scribblecrumb commented on resources/dicts/events/new_cat/general/general.json
> +        "event_text": "n_c, the deputy of o_c, has defected to c_n in the war. {PRONOUN/m_c/subject} decide to keep {PRONOUN/m_c/poss} name.",
"decide" needs to be a VERB tag

2023-05-22 18:00 UTC, Ryos00 approved these changes

2023-05-22 18:00 UTC, merged