pronoun tagging - beach patrols training
ClanGenOfficial/clangen pull request #1414
Opened 2023-04-27 19:30 UTC by sedgestripe

2023-04-28 18:09 UTC, scribblecrumb requested changes
Not an extensive review, but the start of one.  Two repetitive issues were that "themselves" was being treated as "them", which is incorrect.  It also seems like 'null' outcome values were being replaced with actual outcomes, which will screw things up.

2023-04-28 18:09 UTC, scribblecrumb commented on resources/dicts/patrols/beach/training/any.json
> +            "By the end of the patrol, s_c is easily fishing fresh-kill out of the pools with not an ounce of hesitation in {PRONOUN/s_c/poss} movements.",
it seems this got placed in a list index that's supposed to be null?

2023-04-28 18:09 UTC, scribblecrumb commented on resources/dicts/patrols/beach/training/any.json
> +            "app1 tries to poke around in the pools for potential food. Ouch! Oops, that was a sea urchin. app1 limps the whole way home.",
seems to have happened here as well

2023-04-28 18:09 UTC, scribblecrumb commented on resources/dicts/patrols/beach/training/any.json
> +            "Without letting {PRONOUN/r_c/subject} panic, s_c carefully assesses the collapsed dune trapping {PRONOUN/r_c/poss} Clanmate. {PRONOUN/r_c/subject/CAP} {VERB/r_c/point/points} out stable
a subject pronoun tag replaced 'themselves', when it should be a self pronoun tag.   the first four pronouns should be for s_c, not r_c

2023-04-28 18:09 UTC, scribblecrumb commented on resources/dicts/patrols/beach/training/any.json
> +            "As s_c rarely has patience for other cats, r_c tells {PRONOUN/r_c/object} harshly that {PRONOUN/r_c/subject} don't have time for some idiot who got stuck, making s_c resentful as {PRONOU
first pronoun tag should be s_c, not r_c, and last 3 pronoun tags should be s_c, not r_c

2023-04-28 18:09 UTC, scribblecrumb commented on resources/dicts/patrols/beach/training/any.json
> +            "Even though s_c made it out, {PRONOUN/r_c/subject} {VERB/r_c/swear/swears} someone pushed {PRONOUN/r_c/object}, and blame r_c. r_c denies it and says {PRONOUN/r_c/subject} should get s_c
first three and last pronoun tag should be s_c, not r_c

2023-04-28 18:09 UTC, scribblecrumb commented on resources/dicts/patrols/beach/training/any.json
> +            "p_l comes running at {PRONOUN/r_c/poss} yowls, and r_c is soon freed, shaken but unharmed. The cats settle down as {PRONOUN/r_c/subject} {VERB/r_c/comfort/comforts} each other.",
last two tags don't need to be there, the last 'they' is referring to the patrol as a whole

2023-04-28 18:09 UTC, scribblecrumb commented on resources/dicts/patrols/beach/training/any.json
> +            "Without letting {PRONOUN/r_c/subject} panic, s_c carefully assesses the collapsed dune trapping {PRONOUN/r_c/poss} Clanmate. {PRONOUN/r_c/subject/CAP} {VERB/r_c/find/finds} stable footin
first pronoun should be self, not subject.  the first four pronouns should be for s_c, not r_c

2023-04-28 18:09 UTC, scribblecrumb commented on resources/dicts/patrols/beach/training/any.json
> +            "Creeping in as close as possible, s_c purrs to r_c, keeping {PRONOUN/r_c/object} calm as {PRONOUN/r_c/subject} carefully dig down to {PRONOUN/r_c/object}. r_c blinks up at {PRONOUN/r_c/o
second pronoun should be s_c, not r_c.  last two pronouns should be s_c, not r_c

2023-04-28 18:09 UTC, scribblecrumb commented on resources/dicts/patrols/beach/training/any.json
> +            "As s_c rarely has patience for other cats, r_c tells {PRONOUN/r_c/object} harshly that {PRONOUN/r_c/subject} don't have time for some idiot who got stuck, making s_c resentful as {PRONOU
first pronoun tag should be s_c, not r_c, and last 3 pronoun tags should be s_c, not r_c

2023-04-28 18:09 UTC, scribblecrumb commented on resources/dicts/patrols/beach/training/any.json
>          "patrol_id": "bch_train_stuck3",
this patrol likely has all the same problems as the previous two

2023-04-28 18:09 UTC, scribblecrumb commented on resources/dicts/patrols/beach/training/any.json
> +            "s_c tries to remain calm, clawing sand away from {PRONOUN/s_c/poss} muzzle so {PRONOUN/s_c/subject} can breathe. As the shock wears off, {PRONOUN/s_c/subject} {VERB/s_c/realize/realizes}
it replaced a null value again

2023-04-28 18:09 UTC, scribblecrumb commented on resources/dicts/patrols/beach/training/any.json
> +            "Hurt and wheezing, r_c does {PRONOUN/r_c/poss} best to hang on and wait for a patrol, but {PRONOUN/r_c/subject} {VERB/r_c/succumb/succumbs} to {PRONOUN/r_c/poss} injuries and drift to St
replaced a null value again

2023-04-28 18:09 UTC, scribblecrumb commented on resources/dicts/patrols/beach/training/any.json
> +            "r_c eventually manages to pull {PRONOUN/r_c/object} free, but {PRONOUN/r_c/subject}{VERB/r_c/'re/'s} wheezing and injured. It's all {PRONOUN/r_c/subject} can do to find some beach grass
first subject should be self, this seems to be a repeating problem.  probably need to be checking for 'themselves' before 'them'?

2023-04-28 18:09 UTC, scribblecrumb commented on resources/dicts/patrols/beach/training/any.json
> +            "There's nothing to worry about! s_c pads confidently through c_n territory, assured in {PRONOUN/s_c/poss} safety by the strength of c_n borders.",
replaced a null value

2023-05-06 19:39 UTC, Ryos00 approved these changes

2023-05-10 15:47 UTC, Ryos00 approved these changes

2023-05-11 01:44 UTC, merged