Performance-friendly changing of a Sprites opacity
ClanGenOfficial/clangen pull request #1445
Opened 2023-05-08 02:09 UTC by dnbow

I dont know if the fading fog is still wanted as it was a place holder so I removed it

2023-05-08 02:26 UTC, ImLvna commented
swag

2023-05-09 15:14 UTC, Ryos00 approved these changes

2023-05-09 15:25 UTC, keyraven requested changes
This was my original method, however, it does not work properly for pixels that are already partially transparent. set_alpha() sets every pixel to the same value, which is not the intended effect.  The Starclan lineart has a lot of partial transparency.  

I also attempted to leave the lineart unchanged and only apply transparency to the color of the cat, but that effect was deemed too subtle, since it often just looks like the cat was turning black.

2023-05-09 17:24 UTC, dnbow commented
i think this is how i got around that

2023-05-09 17:51 UTC, keyraven requested changes
Concerns:

- You took the method of not applying the opacity to the lineart.  As I said in my previous review, this method was not used because it was too subtle.  The fading effect must be clear from the list screen, not just the profile screen.  It works well enough for ginger cats, but it not clear enough at the list-page level for black and gray cats.  This is not a method I want to use. 
- You are applying the lineart twice. This doubles the partial transparency for all cats with opacity applied. 
- You are applying the lineart after the masks for missing limbs are applied. This means that when cat starts fading, they gain transparent limbs.

2023-05-09 17:51 UTC, keyraven commented on scripts/utility.py
> +        if cat.opacity < 100 and not cat.prevent_fading and game.settings["fading"]
Missing a `;`

2023-05-09 17:51 UTC, keyraven commented on scripts/utility.py
> +            faded_sprite = Surface((spriteSize, spriteSize), pygame.HWSURFACE | pygame.SRCALPHA).convert_alpha()
Surface is not defined. use `pygame.Surface`

2023-05-09 17:55 UTC, dnbow commented
ahhhh i see, ill close it for now but if i find a solution that solves that ill reopen it

2023-05-09 17:55 UTC, closed without merging