Update injuries.json
ClanGenOfficial/clangen pull request #1785
Opened 2023-10-19 19:30 UTC by sand-boa

In the 'frostbite' and 'recovering from birth' injuries, several herbs were in the 'cause_permanent' section rather than the 'herbs' section.

2023-10-19 19:51 UTC, Lixxis approved these changes

2023-10-19 21:53 UTC, Thlumyn requested changes

2023-10-19 21:53 UTC, Thlumyn commented on resources/dicts/conditions/injuries.json
Look at line 815, you're failing the json unit test. Maybe an extra comma?

2023-10-22 17:54 UTC, sand-boa commented on resources/dicts/conditions/injuries.json
Hi! This should be fixed now, thank you.

2023-10-27 03:30 UTC, merged