Mountain-Patrol-Goat
ClanGenOfficial/clangen pull request #1857
Opened 2023-11-01 08:53 UTC by Hamburrgergirl

New patrol for the mountainous biome.

2023-11-01 15:30 UTC, keyraven requested changes

2023-11-01 15:30 UTC, keyraven commented on resources/dicts/patrols/mountainous/border/leaf-fall.json
> +    "season": "leaf-fall",
Season should be a list, so this should be `["leaf-fall"]`

2023-11-01 15:30 UTC, keyraven commented on resources/dicts/patrols/mountainous/border/leaf-fall.json
> +    "patrol_art": null,
There need to be some patrol art, since there is no default option. In the current state, nothing will display (empty patrol art section).  I suggest using the default boarder patrol option, which is `"bord_general_intro"`

2023-11-01 15:30 UTC, keyraven commented on resources/dicts/patrols/mountainous/border/leaf-fall.json
> +    "patrol_art_clean": null,
If the regular patrol art does not contain gore, this line should not be included.

2023-11-01 20:13 UTC, Hamburrgergirl commented on resources/dicts/patrols/mountainous/border/leaf-fall.json
> +    "patrol_art_clean": null,
Thank you! Making all the changes now!

2023-11-01 20:17 UTC, Hamburrgergirl reviewed
Fixed all of the mistakes that were brought to my attention by keyraven

2023-11-02 20:07 UTC, keyraven approved these changes

2023-11-03 05:13 UTC, MaryHawkes approved these changes
I like this patrol! Good season specific content for the mountains, moderate risk of injury, low exp for a border patrol but comparatively safe for a border patrol too, I think it's a good addition to add into the mix that gives good vibes for the biome. Great job!

2023-11-03 15:51 UTC, merged