dark forest thoughts for warriors, leaders, and apprentices
ClanGenOfficial/clangen pull request #1899
Opened 2023-11-16 21:36 UTC by selkirks

added various dark forest for warriors, leaders, and apprentices! noticed they didnt have any so i went a tad bit silly

2023-11-19 06:33 UTC, Lixxis requested changes

2023-11-19 06:33 UTC, Lixxis commented on resources/dicts/thoughts/dead/darkforest/apprentice.json
> +			"Wishes they finished their battle training",
Here is the PRONOUN tag is missing.

2023-11-19 06:33 UTC, Lixxis commented on resources/dicts/thoughts/dead/darkforest/apprentice.json
> +			"Wishes they could put their hunting training to use",
Here is the PRONOUN tag is missing.

2023-11-19 06:33 UTC, Lixxis commented on resources/dicts/thoughts/dead/darkforest/apprentice.json
> +			"Regrets ever disrespecting their mentor",
Here is the PRONOUN tag is missing.

2023-11-19 14:36 UTC, selkirks commented on resources/dicts/thoughts/dead/darkforest/apprentice.json
> +			"Regrets ever disrespecting their mentor",
fixed pronoun tag issues!

2023-11-23 16:21 UTC, Lixxis approved these changes

2023-11-23 16:22 UTC, Lixxis commented on resources/dicts/thoughts/dead/darkforest/apprentice.json
> +			"Wishes they finished their battle training",
I think this is still wrong?

2023-12-01 17:01 UTC, merged