Bugfixing: set weight when creating PatrolEvent
ClanGenOfficial/clangen pull request #1986
Opened 2024-01-04 06:13 UTC by sedgestripe

2024-01-04 06:26 UTC, Thlumyn approved these changes

2024-01-04 09:32 UTC, Lixxis approved these changes

2024-01-04 16:12 UTC, Lixxis requested changes

2024-01-04 16:12 UTC, Lixxis commented on scripts/patrol/patrol.py
> +                weight=patrol.get("weight"),
```suggestion
                weight=patrol.get("weight", 20),
```

The default one is 20 so it should that and not 'None'

2024-01-05 06:53 UTC, Lixxis approved these changes

2024-01-05 06:56 UTC, merged