Pronoun tagging for forest\hunting !
ClanGenOfficial/clangen pull request #2037
Opened 2024-01-20 22:05 UTC by KillerDragain

2024-01-21 01:05 UTC, scribblecrumb commented
You've got some failing tests due to unexpected characters, check through your changes to ensure there aren't any wayward commas or brackets

2024-01-21 07:44 UTC, Thlumyn requested changes

2024-01-21 07:44 UTC, Thlumyn commented on resources/dicts/patrols/forest/hunting/any.json
> +                "text": ""s_c doesn't even hesitate before splitting from the patrol to check on the source of the noise. {PRONOUN/s_c/subject/CAP} quickly {VERB/s_c/regret/regrets} {PRONOUN/s_c/poss
Extra " line 1468

2024-01-24 18:16 UTC, Thlumyn requested changes
There's a lot of spots that say {PRONOUN/r_c/subject} {VERB/r_c/'re/'s} - I can't remember off the top of my head, but we might need to remove the space in between those.

2024-01-24 18:16 UTC, Thlumyn commented on resources/dicts/patrols/forest/hunting/any.json
> +                "text": "The prey is running terribly today. But s_c has patience, and wisely waits for the perfect opportunity instead of getting frustrated. {PRONOUN/s_c/subject/CAP} come back to c
tag "comes"

2024-01-24 18:16 UTC, Thlumyn commented on resources/dicts/patrols/forest/hunting/any.json
> +                "text": "The patrol mostly ignores the Twolegs. As they hunt, they hear a yelp from r_c. {PRONOUN/r_c/subject}{VERB/r_c/'ve/'s} crawled into a metal Twolegs box, and there's nothing {
I think that last tag should actually be them, if it's meaning the Twolegs

2024-01-24 18:16 UTC, Thlumyn commented on resources/dicts/patrols/forest/hunting/any.json
> +                "text": "The patrol mostly ignores the Twolegs. As they hunt, they hear a yelp from r_c. {PRONOUN/r_c/subject}{VERB/r_c/'ve/'s} crawled into a metal Twolegs box, and there's nothing {
I think the last them should stay them to refer to the twolegs

2024-01-24 18:16 UTC, Thlumyn commented on resources/dicts/patrols/forest/hunting/any.json
> +                "text": "With a huge leap, {PRONOUN/app1/subject} {VERB/app1/dart/darts} sideways and pull the tail off a taking flight into blackbird the air. A missed catch, but new nest lining?",
tag "pulls"

2024-01-24 18:16 UTC, Thlumyn commented on resources/dicts/patrols/forest/hunting/any.json
> +                "text": "Nothing's going to escape {PRONOUN/r_c/poss} claws! s_c skids to a halt and then leaps into action, claw just barely catching in the tail of the squirrel {PRONOUN/r_c/subject
tag "pads"

2024-01-24 18:16 UTC, Thlumyn commented on resources/dicts/patrols/forest/hunting/any.json
> +                "text": "app1 skids to a halt and tries to sprint after it, but the bird {PRONOUN/app1/subject} saw escapes {PRONOUN/app1/poss} paws. They chatter angrily at it, and it tries to poop
"They chatter angrily at it, and it tries to poop on them" could be tagged

2024-01-24 18:16 UTC, Thlumyn commented on resources/dicts/patrols/forest/hunting/any.json
> +                "text": "r_c drops into a crouch and lightly stalks towards the vole. {PRONOUN/r_c/subject/CAP} {VERB/r_c/pause/pauses}, waggling {PRONOUN/r_c/poss} haunches before pouncing. {PRONOUN
tag "delivers"

2024-01-24 18:16 UTC, Thlumyn commented on resources/dicts/patrols/forest/hunting/any.json
> +                "text": "s_c drops into a crouch and has to consciously stop {PRONOUN/s_c/poss} tail from swaying in excitement as {PRONOUN/s_c/subject} {VERB/s_c/stalk/stalks} the prey. Once {PRONOU
tag "leaps" and "kills"

2024-01-24 18:16 UTC, Thlumyn commented on resources/dicts/patrols/forest/hunting/greenleaf.json
> +                "text": "s_c makes a stupid mistake, too intent on winning the fight to respect {PRONOUN/s_c/poss} enemy's teeth, and it's tripping over {PRONOUN/s_c/poss} own paws that saves {PRONOU
tag "gives up" and "settles down"

2024-01-24 18:16 UTC, Thlumyn commented on resources/dicts/patrols/forest/hunting/leaf-bare.json
> +        "intro_text": "app1 catches scent of a mouse nearby. But {PRONOUN/app1/subject}{VERB/app1/'re/'s} by {PRONOUN/app1/SELF}, and the chill of leaf-bare has stripped the forest of its green cloak
why is self capitalized?

2024-01-24 18:16 UTC, Thlumyn commented on resources/dicts/patrols/forest/hunting/leaf-bare.json
> +                "text": "As the patrol settles in, tracking mouse scent mostly, s_c wanders back, and as {PRONOUN/s_c/subject} {VERB/s_c/put/puts} a paw down the ground squeaks. {PRONOUN/s_c/subject/
tag "meets"

2024-01-24 18:16 UTC, Thlumyn commented on resources/dicts/patrols/forest/hunting/leaf-bare.json
> +                "text": "Though it tries to escape, r_c is faster and smarter - {PRONOUN/s_c/subject} {VERB/s_c/slam/slams} a paw down on the squirrel's tail before it can go very far, and kill it wi
tag "kills"

2024-01-24 18:16 UTC, Thlumyn commented on resources/dicts/patrols/forest/hunting/leaf-bare.json
> +                "text": "r_c breaks a twig as {PRONOUN/r_c/subject} {VERB/r_c/ready/readies} {PRONOUN/r_c/self} to pounce, and the resulting crack alerts the squirrel. It doesn't even spare them a gl
"It doesn't even spare them a glance as it scurries up the tree and out of sight" you can tag "them" here

2024-01-24 18:16 UTC, Thlumyn commented on resources/dicts/patrols/forest/hunting/leaf-bare.json
> +                "text": "app1 slides into a hunting pose, trying not to focus too hard on making it perfect. {PRONOUN/app1/subject}{VERB/app1/'re/'s} right not to - {PRONOUN/app1/poss} catch is flawl
tag "returns"

2024-01-24 18:16 UTC, Thlumyn commented on resources/dicts/patrols/forest/hunting/leaf-bare.json
> +        "intro_text": "p_l instructs app1 to scent the air, and nods in approval when app1 says {PRONOUN/app1/subject} {VERB/app1/smell/smells} squirrel. Though {PRONOUN/app1/subject} {VERB/app1/do/d
I think those 2nd and 3rd tags should be p_l not app1

2024-01-24 18:16 UTC, Thlumyn commented on resources/dicts/patrols/forest/hunting/leaf-bare.json
> +                "text": "The patrol fans out, some cats climbing, some staying on the ground. The hunt comes to an abrupt end, however, when r_c yowls in fear as {PRONOUN/r_c/subject} {VERB/r_c/plumm
tag "lands"

2024-01-24 18:16 UTC, Thlumyn commented on resources/dicts/patrols/forest/hunting/leaf-bare.json
> +                "text": "p_l is silently furious at r_c {PRONOUN/p_l/subject} {VERB/p_l/find/finds} {PRONOUN/r_c/object}. A snowstorm is no time to go haring off by {PRONOUN/r_c/self}, and it's destr
put "when" back

2024-01-24 18:16 UTC, Thlumyn commented on resources/dicts/patrols/forest/hunting/leaf-bare.json
> +                "text": "p_l watches the cardinal, waiting for the right moment to strike, when it suddenly flits off of the low-hanging branch it was perched on. Without thinking, p_l leaps into the
tag "kills"

2024-01-24 18:16 UTC, Thlumyn commented on resources/dicts/patrols/forest/hunting/leaf-bare.json
> +                "text": "p_l drops into a hunting crouch, watching the cardinal peck at some invisible bit of food. Suddenly, it flies off, and despite p_l's superb reflexes, {PRONOUN/p_l/subject} {V
tag "falls"

2024-01-24 18:16 UTC, Thlumyn commented on resources/dicts/patrols/forest/hunting/leaf-bare.json
> +                "text": "app1 carefully measures {PRONOUN/app1/poss} pawsteps as {PRONOUN/app1/subject} {VERB/app1/drop/drops} into a hunting crouch behind a barren shrub and approach the robin that
tag "approaches"

2024-01-24 18:16 UTC, Thlumyn commented on resources/dicts/patrols/forest/hunting/leaf-bare.json
> +        "intro_text": "p_l leads app1 through the snow-covered forest, showing {PRONOUN/app1/object} how to distribute {PRONOUN/app1/poss} weight across {PRONOUN/app1/poss} paws to avoid sinking and
I think those last 2 tags should be p_l, not app1

2024-01-24 18:16 UTC, Thlumyn commented on resources/dicts/patrols/forest/hunting/leaf-bare.json
> +                "text": "p_l silently demonstrates the right way to crouch and stalk in this unfamiliar wintry world. app1 mimics {PRONOUN/app1/object} faithfully, and springs at the starling from tw
should be p_l, not app1

2024-01-24 18:16 UTC, Thlumyn commented on resources/dicts/patrols/forest/hunting/leaf-bare.json
> +                "text": "r_c presses on through the blinding snow, letting {PRONOUN/r_c/poss} ears guide {PRONOUN/r_c/object}. A faint scent arrives at {PRONOUN/r_c/poss} nose before long - grouse! T
tag "springs"

2024-01-24 18:16 UTC, Thlumyn commented on resources/dicts/patrols/forest/hunting/leaf-bare.json
> +                "text": "s_c makes a stupid mistake, too intent on winning the fight to respect their enemy's teeth, and it's tripping over {PRONOUN/s_c/poss} own feet that saves {PRONOUN/s_c/object}
tag "settles"

2024-01-24 18:16 UTC, Thlumyn commented on resources/dicts/patrols/forest/hunting/leaf-bare.json
> +        "decline_text": "tHE patrol ignores the mouse.",
Capitalization

2024-01-24 18:16 UTC, Thlumyn commented on resources/dicts/patrols/forest/hunting/leaf-bare.json
> +                "text": "As the patrol settles in, tracking mouse scent mostly, s_c wanders back, and as {PRONOUN/s_c/subject} {VERB/s_c/put/puts} a paw down the ground squeaks. {PRONOUN/s_c/subject}
tag "meets"

2024-01-24 18:16 UTC, Thlumyn commented on resources/dicts/patrols/forest/hunting/leaf-bare.json
> +                "text": "These are the times that it really pays to have a hunter of s_c's caliber on the patrol - {PRONOUN/s_c/subject} really go above and beyond, impressing everyone and leaving a
tag "goes"

2024-01-24 18:16 UTC, Thlumyn commented on resources/dicts/patrols/forest/hunting/newleaf.json
> +                "text": "The stocky gray vixen they track down smells of milk, and though she's near double r_c's weight and all of it muscle, {PRONOUN/r_c/subject} {VERB/r_c/meet/meets} her eyes squ
tag "leaps"

2024-01-24 18:16 UTC, Thlumyn commented on resources/dicts/patrols/forest/hunting/newleaf.json
> +                "text": "As the patrol settles in, tracking mouse scent mostly, s_c wanders back, and as {PRONOUN/s_c/subject} {VERB/s_c/put/puts} a paw down the ground squeaks. {PRONOUN/s_c/subject/
tag "meets"

2024-01-24 18:16 UTC, Thlumyn commented on resources/dicts/patrols/forest/hunting/newleaf.json
> +                "text": "While rounds a bend in the path, app1 hears a bird call. Jerking {PRONOUN/app1/poss} head up, {PRONOUN/app1/subject} {VERB/app1/lose/loses} {PRONOUN/app1/poss} footing and sk
tag "skids"

2024-01-24 18:44 UTC, KillerDragain commented
> There's a lot of spots that say {PRONOUN/r_c/subject} {VERB/r_c/'re/'s} - I can't remember off the top of my head, but we might need to remove the space in between those.

Upon searching every file there appeared to be only two. Went ahead and fixed those up.

2024-01-24 19:18 UTC, KillerDragain commented on resources/dicts/patrols/forest/hunting/leaf-bare.json
> +        "intro_text": "app1 catches scent of a mouse nearby. But {PRONOUN/app1/subject}{VERB/app1/'re/'s} by {PRONOUN/app1/SELF}, and the chill of leaf-bare has stripped the forest of its green cloak
i just got really excited /silly

2024-01-25 17:02 UTC, Thlumyn requested changes

2024-01-25 17:02 UTC, Thlumyn commented on resources/dicts/patrols/forest/hunting/leaf-bare.json
> +                "text": "This is bad. When {PRONOUN/p_l/subject} {VERB/p_l/find/finds} r_c, there's barely any warmth left in {PRONOUN/r_c/poss} pelt, and p_l can't wake {PRONOUN/r_c/object}. {PRONOU
Looks like the pronouns tests were failing here - POSS shouldn't be capitalized

2024-01-26 18:50 UTC, Thlumyn approved these changes

2024-01-26 18:50 UTC, merged