fixing an error2
ClanGenOfficial/clangen pull request #2069
Opened 2024-01-27 21:02 UTC by KillerDragain

![image1](https://github.com/ClanGenOfficial/clangen/assets/51783219/27ea9eae-b3a2-449d-bff5-96c5e6556330)

2024-01-28 00:09 UTC, Tiritirimatangi requested changes

2024-01-28 00:09 UTC, Tiritirimatangi commented on resources/dicts/patrols/forest/hunting/newleaf.json
> +                "text": "Though it tries to escape, r_c is faster and smarter - {PRONOUN/r_c/subject} {VERB/s_c/slam/slams} a paw down on the squirrel's tail before it can go very far, and kills it w
excellent bug finding, but this should actually be r_c, not s_c <3

2024-02-07 20:19 UTC, Tiritirimatangi approved these changes
Thank you for catching this!

2024-02-08 16:48 UTC, Lixxis approved these changes

2024-02-08 16:49 UTC, merged