Feature: Clan focus
ClanGenOfficial/clangen pull request #2190
Opened 2024-04-04 19:25 UTC by Lixxis

New feature which allows to influence the general direction of the clan / how the warriors "behave"
This allows following interactions:
* managing roughly resources (prey & herb)
* lowering (or increase) the chance of injuries/illnesses 
* influence the reputation for other clans + outsiders

There are still some smaller bugs which are tracked in the according thread in discord.

2024-04-05 18:47 UTC, Thlumyn requested changes
A couple things, aside from the spelling issues that I noted:
Some of the focus icons have a background, and some do not? 
Once you are done testing the feature, the print statement about rest and recovery should be removed in the future; I think we're getting a few too many print statements building up

2024-04-05 18:47 UTC, Thlumyn commented on resources/game_config.json
> +                "illness will be roughly prevented for every sixt cat - illness is not as easy preventable as injuries",
*sixth

2024-04-05 18:47 UTC, Thlumyn commented on resources/game_config.json
> +            "comment": "Defines how much increase or decrease the relation with other clans."
*with other clans is.

2024-04-06 13:29 UTC, Lixxis commented
@Thlumyn What do you mean with background? All focus types have in the spelling bubble an own picture - or did I miss something?

I also removed or comment the prints out for the merge. The feature was already tested on my branch for several weeks. I want to have the feature on the development branch now, so I don't have to worry about merge conflicts anymore.

2024-04-06 22:07 UTC, sedgestripe requested changes

2024-04-06 22:07 UTC, sedgestripe commented on scripts/events.py
> +            if total_amount == 1:
should be an elif so this doesn't get overwritten in the else block

2024-04-06 22:07 UTC, sedgestripe commented on scripts/events.py
> +            game.herb_events_list.extend(log_text)
append instead of extend since log_text is a string?

2024-04-07 00:24 UTC, Thlumyn commented
> @Thlumyn What do you mean with background? All focus types have in the spelling bubble an own picture - or did I miss something?


![image](https://github.com/ClanGenOfficial/clangen/assets/102194057/0fe467e7-3e48-4520-ad7e-2dd9a508759f)

Like, how some of them have the background image baked in; I tried it on both light mode and dark mode and it doesn't really make a visual difference, but is there a reason why some are like that? If not, it'd be nice for consistency if they were all the same

2024-04-07 18:50 UTC, scribblecrumb commented
> > @Thlumyn What do you mean with background? All focus types have in the spelling bubble an own picture - or did I miss something?
> 
> ![image](https://private-user-images.githubusercontent.com/102194057/320242725-0fe467e7-3e48-4520-ad7e-2dd9a508759f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MTU3NjAsIm5iZiI6MTcxMjUxNTQ2MCwicGF0aCI6Ii8xMDIxOTQwNTcvMzIwMjQyNzI1LTBmZTQ2N2U3LTNlNDgtNDUyMC1hZDdlLTJkZDlhNTA4NzU5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QxODQ0MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzk1ZjE5ZWUyMTM4MTQwZGQ0YWI5MTQ2ZDE0YzYyMTk0Mzk4NDQ4NDM3N2UwYTBhYzFlYWUxY2UyMzViY2MyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N_i5ZCxyWHw83ALXnJm9OBMGdNWu55UWVhGFs4oOXwY)
> 
> Like, how some of them have the background image baked in; I tried it on both light mode and dark mode and it doesn't really make a visual difference, but is there a reason why some are like that? If not, it'd be nice for consistency if they were all the same

Hmm, interesting.  It's been so long since I made the graphics I honestly don't remember if there was a reason.  At this point I'd just guess that it was a mistake on my part, I probably had to make some edits at some point and saved the .pngs with the base layer visible by accident.

2024-04-12 21:43 UTC, sedgestripe approved these changes

2024-04-13 12:42 UTC, Lixxis commented
@Thlumyn is there still something I might have missed / did you found any errors?

2024-04-16 17:06 UTC, Ryos00 approved these changes

2024-04-17 16:09 UTC, Thlumyn approved these changes

2024-04-17 16:09 UTC, merged