stinky foxes test
ClanGenOfficial/clangen pull request #2240
Opened 2024-04-21 13:17 UTC by angelheart04

more will be added - a test for fox smell training patrols

2024-04-26 02:24 UTC, scribblecrumb commented
Hey there!  Looks like you have some json issues.  Probably a trailing comma somewhere.  You'll have to resolve those before we can think about merging this one.

2024-05-03 00:10 UTC, ImLvna commented on resources/dicts/patrols/mountainous/training/any.json
> +            },
Hey there! Remove the comma here ^.^

2024-05-08 15:14 UTC, Thlumyn requested changes
Please test your PRs; this code does not run as it is, the json file that has been modified is not a valid json

2024-05-08 15:14 UTC, Thlumyn commented on resources/dicts/patrols/mountainous/training/any.json
> +            },
```suggestion
            }
```
Remove this extra comma please

2024-05-08 15:14 UTC, Thlumyn commented on resources/dicts/patrols/mountainous/training/any.json
> +            },
```suggestion
            }
```
Remove this extra comma, please

2024-05-08 15:14 UTC, Thlumyn commented on resources/dicts/patrols/mountainous/training/any.json
> +    },
Lines 2308 and 2309 look like they can be removed, for a proper file end

2024-05-27 21:48 UTC, Thlumyn commented
Closing as stale; please reopen once those json fixes are made

2024-05-27 21:48 UTC, closed without merging