Bugfixes
ClanGenOfficial/clangen pull request #2241
Opened 2024-04-21 13:31 UTC by scribblecrumb

- Players no longer get stuck in medicine den purgatory (fixes #2220 #2238 #2232 )
- Buttons now disable/enable properly when closing relationship log on relationship screen (fixes #2214 #2195 )

2024-04-25 18:38 UTC, Lixxis requested changes

2024-04-25 18:38 UTC, Lixxis commented on scripts/screens/RelationshipScreen.py
@scribblecrumb Somehow I can only open the relationship log for the first cat of the list? All other cat's I can't open it.

2024-04-26 02:23 UTC, scribblecrumb commented on scripts/screens/RelationshipScreen.py
Woop, thanks for catching that!  It's fixed now.

2024-04-26 13:50 UTC, Lixxis approved these changes

2024-04-26 13:50 UTC, merged