Add support for 'not_working' thoughts (#2233)
ClanGenOfficial/clangen pull request #2253
Opened 2024-04-25 11:19 UTC by jdowner

This change allows thoughts to be selected based upon a boolean attribute in the thought format called 'not_working'. The 'not_working' status of a cat is an existing feature that returns `true` if the cat has anything more than a minor illness/injury and `false` otherwise.

2024-04-25 11:43 UTC, scribblecrumb commented
This looks good to me!  Feel free to ping the Writing Contributors role, or just Tiri herself, to find a volunteer writer to add some not_working thoughts.

2024-04-25 23:12 UTC, Tiritirimatangi requested changes
I'll get right on to generating some thoughts for you - but i do have a question. The "not_working" tag means the cat has to be in the medicine den, right? Have you coded in an exception for pregnant cats, who stop working to move into the nursery and whose not_working thoughts should probably read different to an injured or ill cat?

2024-04-25 23:33 UTC, Tiritirimatangi commented
I also think this paramter would be exceptionally helpful to have active in the events code too, to encourage writer to give us relationship events that occur between a medicine cat (or med cat app) and their patients, that'd be super cool

2024-04-26 00:38 UTC, scribblecrumb commented
> I'll get right on to generating some thoughts for you - but i do have a question. The "not_working" tag means the cat has to be in the medicine den, right? Have you coded in an exception for pregnant cats, who stop working to move into the nursery and whose not_working thoughts should probably read different to an injured or ill cat?

There's actually an annoying amount of exceptions to the "major+ severity stays in med den" rule (the med den screen is annoying in having to track them all, ugh).  If we're going to have that going on in multiple scripts, then we need to change how it's tracked in the med den screen as well, otherwise we're setting ourselves up for annoyance later.  Personally, I'd prefer if writers simply treated not_working thoughts as "cat is staying in camp, but not necessarily immobile or in the med den".  If you want to get more specific than that, the thought format already has "has_injury", which lets you specify that the cat must have a certain condition in order to get a thought.  Not the most flexible, but it might be the simplest.

2024-04-26 00:40 UTC, scribblecrumb commented
> I also think this paramter would be exceptionally helpful to have active in the events code too, to encourage writer to give us relationship events that occur between a medicine cat (or med cat app) and their patients, that'd be super cool

Since I'm already reformatting moon events, I can look into including this there.  Though, they would be misc moon events that affect relationships, not specifically relationship events.  If you'd like that for relationship events specifically, then that'd be best made as a new enhancement issue as I'm not likely to get into that end of the code.

2024-05-05 07:34 UTC, Lixxis approved these changes

2024-05-06 21:53 UTC, Tiritirimatangi approved these changes

2024-05-07 03:33 UTC, merged