On-death thought rework
ClanGenOfficial/clangen pull request #2303
Opened 2024-05-02 21:13 UTC by Snowstar38

- Death thoughts have their own .json and are now no longer in cats.py
- Now others can introduce additional variants for each type of death thought

2024-05-07 03:47 UTC, scribblecrumb commented
Leader death thoughts don't seem to be working.  I tried having my leader die both naturally via timeskip and manually via profile, either one gave a death thought.  Regular cats do seem to work fine, though.

2024-05-07 03:47 UTC, scribblecrumb requested changes
Leader death thoughts don't seem to be working. I tried having my leader die both naturally via timeskip and manually via profile, either one gave a death thought. Regular cats do seem to work fine, though.

2024-05-16 16:07 UTC, Snowstar38 commented
Ah, I just saw this. When I get home I will take a look and try to fix this. Thanks for telling me!

2024-06-02 19:17 UTC, Snowstar38 commented
@scribblecrumb Hey, I apologize for taking so long to look into this - life stuff. But I just tried to do this and leader thoughts work fine for me? I cloned the dev branch and merged in only these 2 file changes, but my leader death thoughts appear properly for me under both circumstances 🤔

2024-06-04 14:23 UTC, scribblecrumb commented
Hmmm very odd, this is the error I get when my leader dies.

![image](https://github.com/ClanGenOfficial/clangen/assets/115410010/e1fb32f7-4409-422e-8119-6c388ad2ba7a)

It looks like your branch is pretty far behind dev rn too, you may want to sync it.  Perhaps that's making a difference in what I'm experiencing?

![image](https://github.com/ClanGenOfficial/clangen/assets/115410010/21ae3c7f-bed8-4c1f-81aa-784fd36b165e)

2024-06-10 00:42 UTC, Snowstar38 commented
@scribblecrumb 🤦‍♀️ I have no idea how I managed to not notice I hadn't updated the branch, haha!

In any case, once I updated it, I ran into the same issues you'd mentioned. I think they should be fixed now. Thanks for being patient with me about this 😅

2024-06-10 13:08 UTC, scribblecrumb requested changes

2024-06-10 13:08 UTC, scribblecrumb commented on scripts/cat/cats.py
> +            final_thought = event_text_adjust(self, death_thought, self)
make sure that you specify `main_cat=self` in the event_text_adjust arguments, otherwise it'll think `self` is the patrol leader, not the main cat.

2024-06-10 13:08 UTC, scribblecrumb commented on scripts/cat/thoughts.py
> +    def leader_death_thought(self, lives_left, darkforest):
lets add some docstrings to these new functions!  Make sure to include the params with `:param name_of_param: explanation of param`

2024-06-10 13:08 UTC, scribblecrumb commented on scripts/utility.py
> +            replace_dict["m_c"] = (str(Cat.name), choice(Cat.pronouns))
I don't believe this quite works as intended (nor do I think it's a necessary change, you just need to pass the cat as `main_cat`) `Cat` is meant to be the Cat class, not a cat object.  So it looks like you're calling for the Cat class `.name` and `.pronouns`, not a cat object's `.name` and `.pronouns`

2024-06-10 19:02 UTC, Snowstar38 commented
@scribblecrumb I have followed your suggestions! The edit to utility.py was just because I didn't know why it kept crashing aha; you figured out it was the main_cat=self part so now it's unnecessary and I removed it. :)

2024-06-10 21:42 UTC, scribblecrumb approved these changes

2024-06-10 21:42 UTC, merged