Feature: Leader den
ClanGenOfficial/clangen pull request #2378
Opened 2024-05-26 13:51 UTC by scribblecrumb

- Adds Clan symbols.  There is a goal of creating a symbol to correspond with each normal_prefix currently in the game.  As of time of writing, about 200 of 500 are finished.  Clan symbols are assigned first by prefix, then, if no corresponding symbol is available for the prefix, randomly.
- Adds ability to access the Leader's Den
- Leader's Den screen allows for the following:
  - Viewing information (relation, temperament, name, symbol) of Other Clans
  - Choosing an interaction to have with one Other Clan.  One interaction allowed per moon.  Interactions take affect upon timeskip and will influence relations.  Success chance is determined by "distance" between Other Clan temper and Player Clan temper.
  - View information (reputation, name, status, trait, skill) of Outsiders
  - Choose an interaction to have with one Outsider.  One interaction allowed per moon.  Interactions take affect immediately and, if successful, either kill, drive away (remove from cat list and possible future interactions with Clan), or invite in/search for.  Success chance is determined by reputation with Outsiders.
- Adds ability to choose a Clan symbol for the Player Clan
  - In saved Clans that have no symbol, a Clan symbol will be chosen upon loading.  
  - Upon clan creation, the player can choose a symbol for their clan.  The possible symbol list can be filtered by the player to only display symbols with certain attributes.  This will hopefully make it easier to sift through the already large list.  A symbol is also recommended to the player if a symbol exists for their chosen Clan prefix.

TODO:
- [ ] Display Clan symbol on event page
- [ ] Further testing of Outsider mechanics in Leader Den to ensure they function as intended.

2024-05-31 17:52 UTC, Thlumyn requested changes
I'm going to add some screenshots, I noticed some things when testing it out

2024-05-31 17:52 UTC, Thlumyn commented on scripts/screens/LeaderDenScreen.py
> +                          "game.)",
```suggestion
                          "game).",
```

2024-05-31 18:00 UTC, Thlumyn commented
![dead_cat_helper](https://github.com/ClanGenOfficial/clangen/assets/102194057/c0a946ee-981c-4296-bc17-948461d3ad25)
Dead cat shows up as a helper? Not sure if this is intended behavior (as the rest of the clan was dead in this situation) or not, either way thought it worth bringing up.

![deadleader](https://github.com/ClanGenOfficial/clangen/assets/102194057/b0fabe93-8f6d-4856-9a48-0a175761fbbc)
Dead leader was showing up in the den after killing off leader, despite having other living cats that could probably do a better job than a ghost.

![den_image_placement](https://github.com/ClanGenOfficial/clangen/assets/102194057/57bb242f-1ef7-4288-b589-02535e0ba3cc)
With a lot of the den images, the background image cuts real close (or even through, as seen in the cavern background in the previous screenshot) to the text just under it; could we move that text down just a tad? Else, I think we should add some background there so that the text isn't getting interrupted and made hard to read

![invited_loner_wrong_backstory](https://github.com/ClanGenOfficial/clangen/assets/102194057/de98810d-4786-44a7-8907-9ecd2abe1e0a)
Loner invited into the clan; the backstory doesn't quite make sense here. Maybe might be better to add a specific backstory for cats being invited in like this?

![outsider_list_overrun](https://github.com/ClanGenOfficial/clangen/assets/102194057/1bf073a1-76ab-49b2-b65f-84b455ab9f8d)
Cat images in the outsider list overflow to the right

![parenthesis_ic_issue](https://github.com/ClanGenOfficial/clangen/assets/102194057/ffa6a390-1ac9-4253-9962-1fba2d403b3d)
The way this is phrased just seems a bit out of place with the rest of the information in the Events tab; this seems more like debug game information, that breaks the immersion of the game a bit. Maybe something like removing the success or fail part, and just leaving clan relations improved (as long as the player remembers whether they were insulting or complimenting, that should be enough to tell them whether it was success or fail) could still give that information while seeming like an event info that could be in character for the clan.

2024-05-31 18:47 UTC, scribblecrumb commented
> ![dead_cat_helper](https://private-user-images.githubusercontent.com/102194057/335685066-c0a946ee-981c-4296-bc17-948461d3ad25.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNzkzMzQsIm5iZiI6MTcxNzE3OTAzNCwicGF0aCI6Ii8xMDIxOTQwNTcvMzM1Njg1MDY2LWMwYTk0NmVlLTk4MWMtNDI5Ni1iYzE3LTk0ODQ2MWQzYWQyNS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQxODEwMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MmFlOWQxYTkyYWU0YjI3YTdjM2FkNzJiYTFkYWM2NGRiNTQ2MGFjNDFkNGJkYTQyOTBlODM5NmYwNDk0OWJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sKSu_JPmE3p-uY8JA5a9NrdPPzvNR6jRzSGV1bVnClw) Dead cat shows up as a helper? Not sure if this is intended behavior (as the rest of the clan was dead in this situation) or not, either way thought it worth bringing up.
> 
> ![deadleader](https://private-user-images.githubusercontent.com/102194057/335685071-b0fabe93-8f6d-4856-9a48-0a175761fbbc.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNzkzMzQsIm5iZiI6MTcxNzE3OTAzNCwicGF0aCI6Ii8xMDIxOTQwNTcvMzM1Njg1MDcxLWIwZmFiZTkzLThmNmQtNDg1Ni05YTQ4LTBhMTc1NzYxZmJiYy5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQxODEwMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NTdmNGM1YzY1ZjAxMmVhMGU2MTVjZjAyYjZlNGExYjg4YjAwMjVhYTA5ZWQ0MzY1MTNjMjRlM2IzZjA5OTk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tHe_TQQ_ELQPBgDc_N1-CzTgmwPASm6XhjNb_azeCZU) Dead leader was showing up in the den after killing off leader, despite having other living cats that could probably do a better job than a ghost.
> 
Fixed!  I hadn't even considered what it should do if the whole clan was dead haha, so that's now accounted for.  

I'll have a look at the other things you mentioned later (currently on my lunch break from work lol).  Though with regards to the backstories, I'm honestly a bit unsure how to handle those.  Assigning a special backstory means losing a lot of uniqueness that comes from the variety we currently have (unless we create special variations of all of them, which I'm not keen on doing).  We could *maybe* add something extra to the end about the Clan having sought them out specifically?  But with how backstory history is currently set up, that will be a headache.

2024-05-31 23:56 UTC, scribblecrumb commented
> ![den_image_placement](https://private-user-images.githubusercontent.com/102194057/335685073-57bb242f-1ef7-4288-b589-02535e0ba3cc.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxOTk3ODcsIm5iZiI6MTcxNzE5OTQ4NywicGF0aCI6Ii8xMDIxOTQwNTcvMzM1Njg1MDczLTU3YmIyNDJmLTFlZjctNDI4OC1iNTg5LTAyNTM1ZTBiYTNjYy5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQyMzUxMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmQxZTZiY2I3NWMzZTUyYWI3ZDY5NDg1OGE1MWU0NjMxMmQ4ZGI2Yjk4ZjZmZDY1MTY4N2FiYzVkMGVhYjNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JyfdM5fNeA8fyUjq6jqancWasySsSDLK3wlEb709n7M) With a lot of the den images, the background image cuts real close (or even through, as seen in the cavern background in the previous screenshot) to the text just under it; could we move that text down just a tad? Else, I think we should add some background there so that the text isn't getting interrupted and made hard to read
> 
> ![outsider_list_overrun](https://private-user-images.githubusercontent.com/102194057/335685080-1bf073a1-76ab-49b2-b65f-84b455ab9f8d.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxOTk3ODcsIm5iZiI6MTcxNzE5OTQ4NywicGF0aCI6Ii8xMDIxOTQwNTcvMzM1Njg1MDgwLTFiZjA3M2ExLTc2YWItNDliMi1iNjVmLTg0YjQ1NWFiOWY4ZC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQyMzUxMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNWY0N2IzODMzNjA2NDJiODA4OWJjNzMxN2I0MDYwNmI5YTUyOTY3MzdmNTgyMmVjZTZiNTZmMTJlMTY4NDg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3niKoq9-bFaFG2ImkJPe4yEeCon4sU9QzFs99zTqsUo) Cat images in the outsider list overflow to the right
> 
> ![parenthesis_ic_issue](https://private-user-images.githubusercontent.com/102194057/335685082-ffa6a390-1ac9-4253-9962-1fba2d403b3d.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxOTk3ODcsIm5iZiI6MTcxNzE5OTQ4NywicGF0aCI6Ii8xMDIxOTQwNTcvMzM1Njg1MDgyLWZmYTZhMzkwLTFhYzktNDI1My05OTYyLTFmYmEyZDQwM2IzZC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQyMzUxMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYmM5MDcyYTI2Yzc1NDI2NWM5YTNjNGFlOTBmNjgzZGU1ODY2NTdlOWRhMTJkMTk4ODk3ZjcwOWYwODNiZDEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0H9gxQA8lzukJUuOfiEVzKDFMTCPm1vKv4lIH--pf_A) The way this is phrased just seems a bit out of place with the rest of the information in the Events tab; this seems more like debug game information, that breaks the immersion of the game a bit. Maybe something like removing the success or fail part, and just leaving clan relations improved (as long as the player remembers whether they were insulting or complimenting, that should be enough to tell them whether it was success or fail) could still give that information while seeming like an event info that could be in character for the clan.

Fixed!

2024-06-01 16:50 UTC, Thlumyn commented
> > ![dead_cat_helper](https://private-user-images.githubusercontent.com/102194057/335685066-c0a946ee-981c-4296-bc17-948461d3ad25.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNzkzMzQsIm5iZiI6MTcxNzE3OTAzNCwicGF0aCI6Ii8xMDIxOTQwNTcvMzM1Njg1MDY2LWMwYTk0NmVlLTk4MWMtNDI5Ni1iYzE3LTk0ODQ2MWQzYWQyNS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQxODEwMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MmFlOWQxYTkyYWU0YjI3YTdjM2FkNzJiYTFkYWM2NGRiNTQ2MGFjNDFkNGJkYTQyOTBlODM5NmYwNDk0OWJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sKSu_JPmE3p-uY8JA5a9NrdPPzvNR6jRzSGV1bVnClw) Dead cat shows up as a helper? Not sure if this is intended behavior (as the rest of the clan was dead in this situation) or not, either way thought it worth bringing up.
> > ![deadleader](https://private-user-images.githubusercontent.com/102194057/335685071-b0fabe93-8f6d-4856-9a48-0a175761fbbc.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNzkzMzQsIm5iZiI6MTcxNzE3OTAzNCwicGF0aCI6Ii8xMDIxOTQwNTcvMzM1Njg1MDcxLWIwZmFiZTkzLThmNmQtNDg1Ni05YTQ4LTBhMTc1NzYxZmJiYy5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQxODEwMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NTdmNGM1YzY1ZjAxMmVhMGU2MTVjZjAyYjZlNGExYjg4YjAwMjVhYTA5ZWQ0MzY1MTNjMjRlM2IzZjA5OTk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tHe_TQQ_ELQPBgDc_N1-CzTgmwPASm6XhjNb_azeCZU) Dead leader was showing up in the den after killing off leader, despite having other living cats that could probably do a better job than a ghost.
> 
> Fixed! I hadn't even considered what it should do if the whole clan was dead haha, so that's now accounted for.
> 
> I'll have a look at the other things you mentioned later (currently on my lunch break from work lol). Though with regards to the backstories, I'm honestly a bit unsure how to handle those. Assigning a special backstory means losing a lot of uniqueness that comes from the variety we currently have (unless we create special variations of all of them, which I'm not keen on doing). We could _maybe_ add something extra to the end about the Clan having sought them out specifically? But with how backstory history is currently set up, that will be a headache.

Just reading through the current backstories - I think the only ones that seem like a major disconnect to me are the guided ones; could we do new backstory_categories for the invited in cats, to filter out ones like those, instead of writing whole new backstories for them?

2024-06-01 23:23 UTC, scribblecrumb commented
> Just reading through the current backstories - I think the only ones that seem like a major disconnect to me are the guided ones; could we do new backstory_categories for the invited in cats, to filter out ones like those, instead of writing whole new backstories for them?

Alright, I actually ended up just adding a check for the guided backstories.  Now, if a cat being invited in has one they'll just be switched to the "outsider1" backstory (a very basic "cat is from outside the clan").  I decided to do it this way because just randomly choosing a new backstory from the entire range of backstories could lead to some very weird discrepancies.  Namely, a backstory not matching with the type of outsider the cat used to be (loner, kittypet, ect.)

2024-06-02 14:52 UTC, Thlumyn commented
> > Just reading through the current backstories - I think the only ones that seem like a major disconnect to me are the guided ones; could we do new backstory_categories for the invited in cats, to filter out ones like those, instead of writing whole new backstories for them?
> 
> Alright, I actually ended up just adding a check for the guided backstories. Now, if a cat being invited in has one they'll just be switched to the "outsider1" backstory (a very basic "cat is from outside the clan"). I decided to do it this way because just randomly choosing a new backstory from the entire range of backstories could lead to some very weird discrepancies. Namely, a backstory not matching with the type of outsider the cat used to be (loner, kittypet, ect.)

That sounds good 

One other bug I found, hopefully the last; if you exile a leader they still show up in the leader den

2024-06-02 14:55 UTC, scribblecrumb commented
> That sounds good
> 
> One other bug I found, hopefully the last; if you exile a leader they still show up in the leader den

Ah easy to fix at least, got that one taken care of!

2024-06-02 15:48 UTC, Thlumyn approved these changes

2024-06-02 15:50 UTC, merged