Content; Apprentice Thoughts
ClanGenOfficial/clangen pull request #2411
Opened 2024-06-07 22:15 UTC by Clumxy

## About The Pull Request

The pull request adds some apprentice thoughts into the game, such as apprentices interacting with other apprentices, alongside a few pronoun/verb fixes. Simple as that, really.

## Why This Is Good For ClanGen

It is good because:
- Gives Clangen a more lifelike feel, good for people looking for a little slice of life elements.
- Adds more casual elements into the game.

## Proof of Testing

![image](https://github.com/ClanGenOfficial/clangen/assets/88956931/31ca2be2-be75-463f-a7b6-69dff08d4b36)
![image](https://github.com/ClanGenOfficial/clangen/assets/88956931/573bc32f-ae5d-4161-81d4-c52115a7da70)

## Changelog/Credits

- New Apprentice Thoughts

2024-06-07 22:38 UTC, ZtheCorgi reviewed
i think your verb tags may be incorrect - as far as i recall, the plural version should be listed before the singular (ie need/needs instead of needs/need), unless that's been changed

also, line 403 uses he/him pronouns when it should be pronoun tagged

2024-06-07 23:26 UTC, Clumxy commented
> i think your verb tags may be incorrect - as far as i recall, the plural version should be listed before the singular (ie need/needs instead of needs/need), unless that's been changed
> 
> also, line 403 uses he/him pronouns when it should be pronoun tagged

Okay! I'll make some changes. Thanks for the advice!

2024-06-08 16:57 UTC, Clumxy commented
any further review is appreciated!

2024-06-10 16:35 UTC, scribblecrumb requested changes

2024-06-10 16:35 UTC, scribblecrumb commented on resources/dicts/thoughts/alive/apprentice.json
> +            "Is offering an elder to do tick duty",
should reword to "Is offering to do tick duty for an elder", otherwise it sounds like they're trying to make an elder do tick duty

2024-06-10 16:35 UTC, scribblecrumb commented on resources/dicts/thoughts/alive/apprentice.json
> +            "Is in a squabble with r_c over a pebble they both like"
Should change the beginning "Is" to "Gets"

2024-06-24 23:57 UTC, closed without merging