Little fixes
ClanGenOfficial/clangen pull request #2487
Opened 2024-06-17 21:11 UTC by Snowstar38

## About The Pull Request

A few small fixes:

- Use shorten_text_to_fit to dynamically truncate names in patrol screen (this was accidentally missed when I originally updated all shortened text to use shorten_text_to_fit last year)
- Polishes up some text for a new cat patrol
- Fixes gen_death_badger_anylead2 not inserting r_c into history text

## Why This Is Good For ClanGen

## Linked Issues

Fixes: #2486

## Changelog/Credits

2024-06-18 04:22 UTC, scribblecrumb requested changes

2024-06-18 04:22 UTC, scribblecrumb commented on resources/dicts/events/death/general.json
> +            "cats": [ "m_c", "r_c"],
The "cats" list is meant for specifying which cats can have the histories in this block assigned to them.  As r_c doesn't die in this event, I'm fairly certain that, at best, this has no effect (at worst, might break something?)

2024-07-11 18:29 UTC, Ryos00 reviewed
gonna let you add the changes scribble requested before approving, everything else looks fine to me

2024-07-17 22:27 UTC, Snowstar38 commented
@scribblecrumb I removed that bit for you :)

2024-07-31 11:56 UTC, scribblecrumb approved these changes

2024-07-31 11:56 UTC, merged