Fullscreen enhancements (2563) & dynamic buttons
ClanGenOfficial/clangen pull request #2577
Opened 2024-07-08 23:32 UTC by j-gynn

## About The Pull Request

So this started out as fullscreen enhancements and... spiralled.

**Summary of Key Changes**
- Fullscreen isn't crunchy any more! The game will now pick from one of five UI sizes when you request fullscreen gameplay.
- All UI work is now done using the 1x screen scale rather than 2x.
- Buttons! Buttons can now be dynamically generated for the following types:
  - SQUOVAL - the default button shape, you might prefer to call this "pill" or squircle... but squoval sparks joy so here we are
![image](https://github.com/ClanGenOfficial/clangen/assets/48025294/d1727dff-699f-4352-9656-6d54f7d14c54)
  - ROUNDED_RECT - the squarish button
![image](https://github.com/ClanGenOfficial/clangen/assets/48025294/fa27703f-f772-419b-9dd9-08a51c7cfa66)
  - DROPDOWN - Box edition
![image](https://github.com/ClanGenOfficial/clangen/assets/48025294/6da28cde-7b47-46a5-ac15-99216aa8432c)
  - MAINMENU - Th- the main menu buttons.
![image](https://github.com/ClanGenOfficial/clangen/assets/48025294/fdeb52be-cf8b-4ea3-aaad-5f5a7ec05ba4)
  - MENU_LEFT, MENU_MIDDLE, MENU_RIGHT - the little units that make up a lot of our headers
![image](https://github.com/ClanGenOfficial/clangen/assets/48025294/45163bbd-8065-49ea-b10e-7b1426611b1d)

Note that buttons with unique styling or unique elements (arrows, blood, scratches, etc.) are not covered in this rework as they will require a much more nuanced approach. I have also not included the "ladder dropdowns" as there are some that are multiple lines long and this approach can only handle buttons with one row of text.

**Known Issues/Limitations**
- If you update the theming of a UISurfaceImageButton, the surfaces will be wiped.
- Due to things I don't understand about the clangen font, it doesn't want to play nice with being centered. It works fine if you have a word with no descenders (g, y, j, p, q etc), but if there's one of them it yeets into the sky.
- I haven't been able to convert all eligible buttons to using the dynamic enbuttoning. 
  - Pronouns use the CatButton to store a bit of extra data in there.
  - Leader's Den does some quirky stuff with the object ID

## Why This Is Good For ClanGen

## Linked Issues

Closes #2563

## Proof of Testing

![image](https://github.com/ClanGenOfficial/clangen/assets/48025294/caa42085-413b-4d06-ba2c-b6946ddf0a2d)
(running on 125% zoom @ 1920 x 1080 - game running at 1x scale)
![image](https://github.com/ClanGenOfficial/clangen/assets/48025294/90d86d8a-830a-4b9c-8f51-374f70e453e9)
(running on 100% zoom @ 1920 x 1080 - game running at 1.5x scale)

[Link to the Discord testing channel](https://discord.com/channels/1003759225522110524/1260014395560300614)

## Changelog/Credits

Fullscreen rework & Dynamic Buttons Part 1

2024-07-13 03:50 UTC, scribblecrumb commented
Event screen merge left you with some conflicts ;-; godspeed soldier

2024-07-17 11:46 UTC, j-gynn commented
So, so many bugs. Please hold.

2024-07-31 14:01 UTC, archanyhm commented
Is it possible to split the dynamic buttons and the fullscreen enhancements up or would that be a lot of work for you? I'd usually argue that those two things are different enough to be in separate PRs, but I don't want to impose disproportionate amounts of work here.

2024-07-31 14:03 UTC, j-gynn commented
> Is it possible to split the dynamic buttons and the fullscreen enhancements up or would that be a lot of work for you? I'd usually argue that those two things are different enough to be in separate PRs, but I don't want to impose disproportionate amounts of work here.

Teeechnically yes, but only if you're willing to accept that the fullscreen changes will include quite a few visual artifacts. The fullscreen PR is blocked by/dependent on the dynamic buttons & boxes in order to not do Weird Things

2024-07-31 16:25 UTC, j-gynn commented
Bug found: when you load an existing clan for the first time, EventsScreen doesn't correctly load the past moon's events. It seems to load the relationship events fine, and the next moon loads as expected. Investigating.

2024-07-31 16:46 UTC, j-gynn commented
Buggo squished

2024-08-01 13:23 UTC, scribblecrumb commented on resources/placements.json
Am I right that this was just an auto-reformat thing?  I'm not a huge fan of how it reformatted, it's kinda *harder* to read now.

2024-08-01 14:33 UTC, j-gynn commented on resources/placements.json
Regrettably yes, I didn't make it do that. As far as I can tell this was some kind of autoformatter and yes - it is definitely less readable. If you like, I can go through and manually fix it and see if that fixes it on commit.

2024-08-01 15:32 UTC, j-gynn commented on resources/placements.json
I think? I have fixed it @scribblecrumb

2024-08-03 13:31 UTC, scribblecrumb requested changes
You're so cool for figuring all this out and I'm super excited to see it PR'd!  That said, here's what I noticed while playtesting.

![image](https://github.com/user-attachments/assets/66cdd28d-5f78-48c6-aa9c-96387dce501e)

Looks like unavailable main menu buttons are squovals on one side and rounded_rect on the other.

![image](https://github.com/user-attachments/assets/e4026a91-11d2-4c1e-897b-d9a581251bb3)

Not sure what's happening with the scroll bar here (windowed mode), but the arrow buttons seem very weird.  Eventually they'll get replaced by our more customized scrollbar, but until I get to this page in the refactor it'd be good to try and get the "default" scrollbar looking closer to how it used to.

![image](https://github.com/user-attachments/assets/ec341ef9-5d40-48e1-8c51-6de16ef1e346)

Fullscreen version has no arrows at all (or maybe the top of one at the bottom button?)

![image](https://github.com/user-attachments/assets/c75461bd-914a-48ee-ad6d-2ffd1ce9af1b)

The 'f' in info is being cut off in windowed mode. (this seems to happen with all F's)

![image](https://github.com/user-attachments/assets/49a7dee1-072d-4028-8652-9820559dbcc4)

Slightly less cut off in fullscreen.

![image](https://github.com/user-attachments/assets/06d0ce5c-acf8-42b8-bdd9-31a022ddf99d)

(fullscreen) The tabs look to be a single pixel too far to the left.

![image](https://github.com/user-attachments/assets/b1ebc7db-7bf6-4933-bbda-2134f2aa7a75)

Not a huge fan of how the menu buttons changed visually (the bars between each button always being visible), I'd prefer if they could stay consistent with their old visual.  I know this is probably to avoid having *another* type of button, but <3 know that I appreciate your hard work here and that also someone (maybe me?) tried to change it to that a long time ago and it wasn't a popular change At All.  I can already hear the complaints echoing.  Additionally, the middle buttons have the shadow on all sides, while the end buttons only have shadow on top and right.  This should also be made consistent.  Patrol text also looks slightly offcenter to the right.

![image](https://github.com/user-attachments/assets/54f81beb-166a-4732-a888-efd553afdc99)

Tabs have vertically stretched text.

![image](https://github.com/user-attachments/assets/9aa6c014-c4d6-4b27-a28f-f9de7ad6b71a)

sprite inspector has a MASSIVE fav star, probably not how it's meant to be?

![image](https://github.com/user-attachments/assets/f8e70774-0bc6-49da-8589-4650c7373ca9)

(fullscreen) sprite inspector page has no checkboxes in this mode.

![image](https://github.com/user-attachments/assets/aeb81227-77df-4284-97ce-1732b03fde84)

(fullscreen) Conditions box is one pixel too high.

![image](https://github.com/user-attachments/assets/8c537e6e-40bb-4037-9085-cb545f587126)
Some buttons are a darker grey color scheme?  We want to use the lighter one.

![image](https://github.com/user-attachments/assets/020993c5-beb2-4343-b1e1-6060933ea27b)

Self-explanatory

![image](https://github.com/user-attachments/assets/737153c8-4de2-4370-b788-94c8f68d0a39)

Hard to demonstrate with a screenshot, but the next/prev buttons seem to be layered below the image, which causes them to only trigger a hover state when hovering their top half.

![image](https://github.com/user-attachments/assets/188f46ab-42a5-4ef6-985c-bbde5c7edd7d)

No seasons tabs in fullscreen or windowed?

![image](https://github.com/user-attachments/assets/ac915a45-4dfb-4f7c-8c52-8cc17e4ae52e)

Choose random button should be squoval

![image](https://github.com/user-attachments/assets/79ca37e2-459a-4d10-a6d6-9edb46a71336)

Clan name should be left aligned with the clan info.  Additionally, it scooted? to the right a couple times when I was clicking through symbols?  Doesn't happen consistently though.

![image](https://github.com/user-attachments/assets/a64e8982-8580-461f-9a5c-e41d3c45c344)

Something funky happening with the filter window.

Other things:
- When opening the warriors den, the focus buttons visibly blink from a shorter version to a longer version, should probably have another look at how these are created in screen switch
- Could we get a fullscreen toggle on the clan settings page as well?
- Would love it if the camp BG was *always* the fullscreen BG when playing.  Blank color BG is boring and not particularly immersive.  I also find it a bit jarring when moving between screens.

2024-08-06 03:30 UTC, scribblecrumb commented
![image](https://github.com/user-attachments/assets/6e508efc-4a6e-4c33-8885-67bed3b33d81)
tooltip box here should be wider

![image](https://github.com/user-attachments/assets/2a950774-7c07-4462-a411-7ca8ea6640c8)
Unknown Residence displays the wrong BG

![image](https://github.com/user-attachments/assets/d17ffd24-71a1-41d6-9908-3cb6beaf1387)
Event list scrollbar is a bit fucked in both full and windowed
Event list buttons (cat buttons and profile buttons) don't switch to hover state properly (sidenote: it's so cool to see the profile buttons actually use the clangen font)

![image](https://github.com/user-attachments/assets/bda3b134-cd34-45cd-a151-f5da5a582a7a)
The lighter rectangles on the event list look to be just slightly the wrong color, they should be the same color as the light mode BG

![image](https://github.com/user-attachments/assets/5e487c0a-d622-4622-86b1-5e631ccf0523)
Fullscreened patrol artwork is still crunchy.  Is this a limitation or can it be remedied?

![image](https://github.com/user-attachments/assets/32e18abd-f09c-4af2-ad69-9b4df506aaf9)
Header clan name isn't vertically centered in fullscreen

![image](https://github.com/user-attachments/assets/3ea94ebc-24d0-49c4-82c2-003dc48230b3)
uh oh (windowed)

![image](https://github.com/user-attachments/assets/d67bfbe1-c94f-42fd-bae2-669288564e5d)
UH OH  (windowed)


I'm also noticing that our Prev/Next cat buttons aren't visually consistent across different screens (profile vs. rel page, for example).

2024-08-08 13:18 UTC, scribblecrumb commented
There's a pretty significant lag when leaving the settings + info page, seems much more pronounced when in fullscreen

![image](https://github.com/user-attachments/assets/f1d04eb3-7055-4fd1-a837-67e2f4bae486)
There seems to be a white outline around the camp cats while in fullscreen, is this just a limitation or can we prevent it somehow?

![image](https://github.com/user-attachments/assets/e8b6e75c-3471-4782-bffa-dc3dc48b1b09)
Still broken in windowed mode after using the F4 toggle.  Kinda does the opposite when using the toggle to go from windowed to full (box becomes too small)  If this is just something we have to deal with with that toggle, then so be it, but it's not too ideal for debugging purposes.  I'll say, this seems to be the only screen where that box breaks.  Choose mate uses the same box but doesn't have this issue, however Change mentor *does* have the same issue.  Relationships screen problem seems to be fixed.

Allegiances page seems to open with a scrollbar even when the list isn't long enough to need one.  Scrolling all the way up then makes the bar disappear.

![image](https://github.com/user-attachments/assets/07af8ea5-b390-498c-b90b-5ff711bce68b)
We're overlapping a tad

2024-09-30 03:05 UTC, scribblecrumb approved these changes

2024-09-30 03:05 UTC, merged