Content: Add + Fix Leader SC Ceremonies + Loner Names
ClanGenOfficial/clangen pull request #2666
Opened 2024-09-08 06:48 UTC by izzyphobic

Fixes some of the leader ceremonies that were supposed to be generating for a starclan trait generating for a leader trait, plus adds some new ceremonies and 100+ new loner names.

## About The Pull Request

Fixes some of the leader ceremonies that were supposed to be generating for a certain Starclan trait instead generating for a leader trait (a SC cat that had the trait Calm could generate a ceremony as though they were Sneaky), plus adds some NEW ceremonies and 100+ new loner names.

## Why This Is Good For ClanGen

I had heard some new Leader Ceremonies were needed for some traits, so I got to work on some! Additionally, it was noticed that in a previous merge there may have been a misunderstanding in how the Leader Ceremony traits work, so every cat should now instead get a ceremony that actually matches the trait they have.

https://discord.com/channels/1003759225522110524/1101276997751164948/1281474120889929821

## Proof of Testing

![image](https://github.com/user-attachments/assets/c3ebaabe-a048-4e7f-abf9-36dcfef27378)
![image](https://github.com/user-attachments/assets/f6a1a981-51f1-4d1b-9277-0f40b093b4f4)
![image](https://github.com/user-attachments/assets/1710ba4b-b892-4d6d-a2d9-de70a983828d)
![image](https://github.com/user-attachments/assets/4933fd13-ee2c-434c-8612-d497184cf3e7)

## Changelog/Credits

2024-09-08 19:44 UTC, scribblecrumb requested changes

2024-09-08 19:44 UTC, scribblecrumb commented on resources/dicts/lead_ceremony_sc.json
> +          "text": "m_c, recognized for {PRONOUN/m_c/poss} steady composure, greeted r_c with a courteous nod as {PRONOUN/m_c/subject} approached. Approval alight in {PRONOUN/r_c/poss} expression, r_c
```suggestion
          "text": "m_c, recognized for {PRONOUN/m_c/poss} steady composure, greeted r_c with a courteous nod as {PRONOUN/r_c/subject} approached. Approval alight in {PRONOUN/r_c/poss} expression, r_c bestows upon  m_c a life for [virtue]. As it settled within {PRONOUN/m_c/object}, {PRONOUN/m_c/subject} could feel a subtle, yet powerful shift within, one of fiery initiative.",
```
pronoun tag seemed to be directed toward the wrong cat, and a little sentence break to help with readability

2024-09-08 19:44 UTC, scribblecrumb commented on resources/dicts/lead_ceremony_sc.json
> +          "text": "r_c approaches m_c with narrowed eyes, slightly unsettled by {PRONOUN/m_c/poss} aloofness. m_c is startled by the radiant warmth that surged through {PRONOUN/m_c/poss} chest as {PR
```suggestion
          "text": "r_c approaches m_c with narrowed eyes, slightly unsettled by {PRONOUN/m_c/poss} aloofness. m_c is startled by the radiant warmth that surges through {PRONOUN/m_c/poss} chest as {PRONOUN/m_c/object} {VERB/r_c/are/is} granted a life for [virtue], and for the first time in a long while, a soft smile softens {PRONOUN/m_c/poss} cold demeanor.",
```
tense fix

2024-09-08 19:44 UTC, scribblecrumb commented on resources/dicts/lead_ceremony_sc.json
> +          "text": "r_c gazed at the lonesome leader with a deep sympathy as {PRONOUN/r_c/subject} approached, sensing the weight of {PRONOUN/m_c/poss} solitude. m_c's eyes begin to well up as a life
```suggestion
          "text": "r_c gazes at the lonesome leader with a deep sympathy as {PRONOUN/r_c/subject} approach, sensing the weight of {PRONOUN/m_c/poss} solitude. m_c's eyes begin to well up as a life for [virtue] flows through {PRONOUN/m_c/object}, a warm embrace that wards off the cold isolation, even if for a brief moment.",
```

2024-09-08 19:44 UTC, scribblecrumb commented on resources/dicts/lead_ceremony_sc.json
> +          "text": "m_c's ears perk up as {PRONOUN/m_c/subject} {VERB/m_c/begin/begins} to hear a deep, resonant rumbling. Reciprocating the intense purr, m_c gently bumps heads with r_c, a warrior kn
```suggestion
          "text": "m_c's ears perk up as {PRONOUN/m_c/subject} {VERB/m_c/begin/begins} to hear a deep, resonant rumbling. Reciprocating the intense purr, m_c gently bumps heads with r_c, a warrior known for the endless love {PRONOUN/r_c/subject} {VERB/r_c/hold/holds} for {PRONOUN/r_c/poss} Clan. A warm, sweet feeling cascades over m_c as {PRONOUN/m_c/subject} {VERB/m_c/receive/receives} a life for [virtue].",
```

2024-09-09 02:30 UTC, izzyphobic commented
Committed your changes, should be okay now, let me know if there is anything else :3

2024-09-09 02:54 UTC, scribblecrumb approved these changes

2024-09-09 02:54 UTC, merged