CONTENT: Skill-specific outcomes for Leader's Den
ClanGenOfficial/clangen pull request #2673
Opened 2024-09-11 21:14 UTC by LaurBee

## About The Pull Request
**Adds five new Leader's Den outcomes involving the Hunting skill.**
2x Outsider invites
1x Exile invite
1x Outsider drive-off
1x Outsider hunt down

## Why This Is Good For ClanGen
As mentioned in the Discord, Leader's Den events are fairly basic. These new outcomes should hopefully add a bit more flavour to the feature
Discord Conversation Link: https://discord.com/channels/1003759225522110524/1101276997751164948/1283142501162684487

## Proof of Testing
![Exile_Invite1](https://github.com/user-attachments/assets/b010da3c-3196-4020-a05f-8601b2bf857d)
![Outsider_DriveOff1](https://github.com/user-attachments/assets/13127359-6142-472c-a050-3b8af6363b56)
![Outsider_HuntDown1](https://github.com/user-attachments/assets/7cc11a81-a49a-43cd-980c-8bcd55f0599f)
![Outsider_Invite1](https://github.com/user-attachments/assets/57f179b0-61df-4b7c-a365-cdaa1ec5f57c)
![Outsider_Invite2](https://github.com/user-attachments/assets/1c5af840-d3bd-49a7-bbfd-669271bea2fb)

## Changelog/Credits
Added new Leader's Den outcomes

2024-09-11 21:43 UTC, scribblecrumb requested changes
Sorry to request more work from you lol, the only thing really required to gain approval is the hunting skill fixes.  If you aren't interested in adding the alternate events I suggested or would rather add those via a second PR, then just let me know!

2024-09-11 21:43 UTC, scribblecrumb commented on resources/dicts/events/leader_den/success/outsider.json
> +        "HUNTER,4"
```suggestion
      "skill": [
        "HUNTER,3"
```
Skill tags allow for the tagged skill type of the tagged level *and* any higher levels, so you don't need to tag for both `Hunter,3` and `Hunter,4`.  Just `Hunter,3` will cover both of them.  Go ahead and make this adjustment on all your new hunter events.

2024-09-11 21:43 UTC, scribblecrumb commented on resources/dicts/events/leader_den/success/outsider.json
> +    "event_text": "Some of c_n's best hunters challenge m_c to a hunt-off. The stakes are simple: if c_n wins, m_c leaves the territory; if m_c wins, then {PRONOUN/m_c/subject} will be allowed to hun
might i ask for another version of this event as a drive off event where the outsider loses and leaves?  As well as, perhaps, a failed invite version where the outsider wins and continues living outside of the Clan instead of asking to join?

2024-09-11 21:43 UTC, scribblecrumb commented on resources/dicts/events/leader_den/success/outsider.json
> +      "status": ["loner", "rogue", "kittypet"],
a version of this event for exiled outsiders could be nice!  an exile sneaking back into the territory to hunt their old clan's prey is an interesting concept

2024-09-11 21:49 UTC, LaurBee commented on resources/dicts/events/leader_den/success/outsider.json
> +        "HUNTER,4"
Gonna be 100% honest, did **_not_** know this LOL. Thank you for telling me

2024-09-11 21:52 UTC, LaurBee commented
I can definitely get a few more variants made! I was actually already thinking about doing a chase variant for the hunt-off, so I'll get right to that!

2024-09-11 23:01 UTC, LaurBee commented on resources/dicts/events/leader_den/success/outsider.json
> +    "event_text": "Some of c_n's best hunters challenge m_c to a hunt-off. The stakes are simple: if c_n wins, m_c leaves the territory; if m_c wins, then {PRONOUN/m_c/subject} will be allowed to hun
Done and done!

2024-09-11 23:03 UTC, LaurBee commented on resources/dicts/events/leader_den/success/outsider.json
> +      "status": ["loner", "rogue", "kittypet"],
Did two versions of this: one where the exile is driven off, and one where they're killed. May also try to make an invite variant sometime in the future

2024-09-12 02:52 UTC, scribblecrumb approved these changes

2024-09-12 02:53 UTC, merged