[BUGFIX] Default string, this should never appear #2703
ClanGenOfficial/clangen pull request #2706
Opened 2024-09-19 04:39 UTC by PoppyBlossom

## About The Pull Request
This pull request addresses an issue where the game lacked an unrestricted "dislike high" interaction after the only nonrestrictive "dislike high" was demoted to medium in #2690. So I added a few more interactions to compensate for this. The error message for no interaction was changed from an error to a warning, and the default string interaction was removed since this issue doesn't significantly impact gameplay.

## Linked Issues
fixes: #2703

## Proof of Testing
The issue no longer occurs and I ran for an additional 200 moons just to make sure.

## Changelog/Credits
Fixed default string.
_Can I be added to the credits list by the way_

2024-09-19 04:43 UTC, PoppyBlossom commented
Look what I found!!!
![image](https://github.com/user-attachments/assets/783f58a5-25ca-43a5-94a7-c14155188797)
**_DISCLAMER: I did this just for fun, and out of curiosity_**

2024-09-19 12:39 UTC, scribblecrumb requested changes

2024-09-19 12:39 UTC, scribblecrumb commented on resources/dicts/relationship_events/normal_interactions/platonic/decrease.json
> +			"r_c was find spreading rumors about m_c stealing stuff from {PRONOUN/r_c/object}.",
```suggestion
			"r_c was found spreading rumors about m_c stealing stuff from {PRONOUN/r_c/object}.",
```

2024-09-19 12:39 UTC, scribblecrumb commented on resources/dicts/relationship_events/normal_interactions/platonic/decrease.json
> +			"r_c was caught hiding m_c belongings.",
```suggestion
			"r_c was caught hiding m_c's belongings.",
```

2024-09-19 22:20 UTC, scribblecrumb commented
Feel free to add yourself to the credits_text.json!

2024-09-20 01:50 UTC, scribblecrumb approved these changes

2024-09-20 01:51 UTC, merged