[BUGFIX] various text fixes
ClanGenOfficial/clangen pull request #2712
Opened 2024-09-20 20:44 UTC by selkirks

## About The Pull Request

fixes various texts in thoughts,patrols, and events. pronoun tagging, verb tagging, m_c issues are fixed

## Linked Issues
https://github.com/ClanGenOfficial/clangen/issues/1818#issuecomment-2307959642
https://github.com/ClanGenOfficial/clangen/issues/1818#issuecomment-2311443633
https://github.com/ClanGenOfficial/clangen/issues/1818#issuecomment-2342369850
https://github.com/ClanGenOfficial/clangen/issues/1818#issuecomment-2342383408
https://github.com/ClanGenOfficial/clangen/issues/1818#issuecomment-2345217669
https://github.com/ClanGenOfficial/clangen/issues/1818#issuecomment-2345222934
https://github.com/ClanGenOfficial/clangen/issues/1818#issuecomment-2347941678
https://github.com/ClanGenOfficial/clangen/issues/1818#issuecomment-2351359475
https://github.com/ClanGenOfficial/clangen/issues/1818#issuecomment-2354412134
https://github.com/ClanGenOfficial/clangen/issues/1818#issuecomment-2361322678

## Proof of Testing
![image](https://github.com/user-attachments/assets/15abf699-3538-46e8-9393-1eb591aedd2a)

## Changelog/Credits
fixes some text errors

2024-09-21 00:33 UTC, scribblecrumb requested changes

2024-09-21 00:33 UTC, scribblecrumb commented on resources/dicts/thoughts/alive/general.json
> +        "Brought r_c a herb to identify"
```suggestion
        "Brought r_c an herb to identify"
```
This should actually be "an" as "herb" is pronounced with a beginning vowel sound despite the first letter being a consonant.

2024-09-21 08:52 UTC, keplerstelescope reviewed
some edits! mostly edits to what was already there, rather than to what was changed in this PR. planning on making a PR to this with even more fixes to other bits of the code!

2024-09-21 08:52 UTC, keplerstelescope commented on resources/dicts/patrols/beach/med/leaf-fall.json
> +                "text": "It takes little intelligence to recognize deathberries but a great deal to collect them anyway. If s_c can dry them out, these berries will be sufficient for c_n for years to
```suggestion
                "text": "It takes little intelligence to recognize deathberries, but a great deal to collect them. If s_c can dry them out, these berries will be sufficient for c_n for years to come. By using {PRONOUN/s_c/poss} weight to snap off one of the bush's branches and then carefully carrying it back to camp, s_c manages to bring them safely home.",
```
edit to make the sentence flow more smoothly

2024-09-21 08:52 UTC, keplerstelescope commented on resources/dicts/patrols/general/medcat.json
> +                "text": "s_c laid in the patch of sun, huffing, {PRONOUN/s_c/subject} deserved a nice break, away from all {PRONOUN/s_c/poss} Clanmates. {PRONOUN/s_c/subject/CAP} could always just sa
```suggestion
                "text": "s_c laid in the patch of sun, huffing. {PRONOUN/s_c/subject/CAP} deserved a nice break, away from all {PRONOUN/s_c/poss} Clanmates. {PRONOUN/s_c/subject/CAP} could always just say {PRONOUN/s_c/subject} failed to find any herbs after all.",
```
ditto to last suggestion

2024-09-21 08:52 UTC, keplerstelescope commented on resources/dicts/patrols/general/medcat.json
> +                "text": "p_l's eyes go wide, fur puffing up, and tells r_c that {PRONOUN/r_c/poss} dream is a warning of death and destruction, thoroughly freaking r_c out and bringing unease to the
```suggestion
                "text": "p_l's eyes go wide, fur puffing up, and {PRONOUN/p_l/subject} {VERB/p_l/tell/tells} r_c that {PRONOUN/r_c/poss} dream is a warning of death and destruction, thoroughly freaking r_c out and bringing unease to the patrol.",
```

2024-09-21 08:52 UTC, keplerstelescope commented on resources/dicts/patrols/general/medcat.json
> +                "text": "p_l's eyes go wide, fur puffing up, and tells the apprentice that {PRONOUN/app1/poss}'s dream is a warning of death and destruction, thoroughly freaking app1 out.",
```suggestion
                "text": "p_l's eyes go wide, fur puffing up, and {PRONOUN/p_l/subject} {VERB/p_l/tell/tells} the apprentice that {PRONOUN/app1/poss}'s dream is a warning of death and destruction, thoroughly freaking app1 out.",
```

2024-09-21 08:52 UTC, keplerstelescope commented on resources/dicts/patrols/mountainous/training/leaf-fall.json
> +                    "text": "s_c can't help but be overly fascinated as p_l speaks about how a warrior was so powerful that they needed to tear a hole in Silverpelt just to be able to stop them. s_c
```suggestion
                    "text": "s_c can't help but be overly fascinated as p_l speaks about how a warrior was so powerful that a hole needed to be torn in Silverpelt just to be able to stop them. s_c hopes to one day be that powerful.",
```
original sentence reads as "a warrior so powerful that the warrior needed to tear a hole in Silverpelt"

2024-09-21 08:52 UTC, keplerstelescope commented on resources/dicts/relationship_events/normal_interactions/dislike/increase.json
> +            "m_c wonders how easy it'd be to convince the rest of the Clan to agree exiling r_c is a good move...",
```suggestion
            "m_c wonders how easy it'd be to convince the rest of the Clan to agree that exiling r_c is a good move...",
```

2024-09-21 08:52 UTC, keplerstelescope commented on resources/dicts/thoughts/alive/general.json
> +        "main_living_status": [
this thought group is in thoughts/alive, so this is superfluous, removing it would make for cleaner code

2024-09-21 08:52 UTC, keplerstelescope commented on resources/dicts/thoughts/alive/general.json
> +            "Dosen't regret {PRONOUN/m_c/poss} choice to leave {PRONOUN/m_c/poss} old Clan",
```suggestion
            "Doesn't regret {PRONOUN/m_c/poss} choice to leave {PRONOUN/m_c/poss} old Clan",
```

2024-09-21 19:10 UTC, keplerstelescope commented
related to this PR, is there a standard for how mossball/moss-ball should be written? in various bits of code, it's written as both of those, and a couple times as "moss ball" too

2024-09-21 19:17 UTC, selkirks commented
> related to this PR, is there a standard for how mossball/moss-ball should be written? in various bits of code, it's written as both of those, and a couple times as "moss ball" too

i asked this a few hours ago in discord haha. its moss ball which i will fix

2024-09-22 01:12 UTC, scribblecrumb approved these changes

2024-09-22 01:12 UTC, merged