Pronoun - Conditions & death reactions
ClanGenOfficial/clangen pull request #2728
Opened 2024-09-24 17:51 UTC by j-gynn

## About The Pull Request

Pronoun checks cover `dicts/conditions/*`, `dicts/events/death/death_reactions/*` and `resources/dicts/events/death/mountainous.json`.

Also fixed a potential crash situation with grief strings, where a trait could have strings for the opposite `body` status & attempt to retrieve an empty value.

## Proof of Testing

## Changelog/Credits

2024-09-24 23:38 UTC, scribblecrumb requested changes

2024-09-24 23:38 UTC, scribblecrumb commented on resources/dicts/conditions/condition_got_strings/gain_congenital_condition_strings.json
> +        "m_c fits in perfectly at first, but as {PRONOUN/m_c/subject} {VERB/m_c/grow/grows} and open {PRONOUN/m_c/poss} eyes, it becomes clear that to m_c, there's no difference between having {PRONO
```suggestion
        "m_c fits in perfectly at first, but as {PRONOUN/m_c/subject} {VERB/m_c/grow/grows} and {VERB/m_c/open/opens} {PRONOUN/m_c/poss} eyes, it becomes clear that to m_c, there's no difference between having {PRONOUN/m_c/poss} eyes closed or open."
```

2024-09-24 23:38 UTC, scribblecrumb commented on resources/dicts/conditions/healed_and_death_strings/illness_death_strings.json
> +        "m_c's case of heat stroke has killed her."
```suggestion
        "m_c's case of heat stroke has killed {PRONOUN/m_c/object}."
```

2024-09-24 23:38 UTC, scribblecrumb commented on resources/dicts/conditions/healed_and_death_strings/illness_death_strings.json
> +        "m_c's festering wound has finally killed her."
```suggestion
        "m_c's festering wound has finally killed {PRONOUN/m_c/object}."
```

2024-09-24 23:38 UTC, scribblecrumb commented on resources/dicts/conditions/healed_and_death_strings/illness_healed_strings.json
>          "m_c's paws no longer feel quite so heavy. {PRONOUN/m_c/subject/CAP} can tell that {PRONOUN/m_c/subject} still need to eat more, but at least the situation isn't as dire.",
```suggestion
        "m_c's paws no longer feel quite so heavy. {PRONOUN/m_c/subject/CAP} can tell that {PRONOUN/m_c/subject} still {VERB/m_c/need/needs} to eat more, but at least the situation isn't as dire.",
```

2024-09-24 23:38 UTC, scribblecrumb commented on resources/dicts/events/death/mountainous.json
> +        "event_text": "m_c sneaks out of camp but finds {PRONOUN/m_c/self} lost in the strange, angular tunnels that lead out into the territory. The Clan search for {PRONOUN/m_c/object} in the morni
```suggestion
        "event_text": "m_c sneaks out of camp but finds {PRONOUN/m_c/self} lost in the strange, angular tunnels that lead out into the territory. The Clan searches for {PRONOUN/m_c/object} in the morning to no avail. The leftover scent of blood and mountain weasel serves as an intense warning to the other kits.",
```

2024-09-24 23:38 UTC, scribblecrumb commented on resources/dicts/events/death/death_reactions/parent/parent_dislike.json
> +            "r_c keeps up appearances, soothing the fur of {PRONOUN/r_c/poss} dead kit and sitting vigil, but {PRONOUN/r_c/subject} {VERB/r_c/don't/doesn't} care that m_c is dead. {PRONOUN/r_c/subjec
```suggestion
            "r_c keeps up appearances, smoothing the fur of {PRONOUN/r_c/poss} dead kit and sitting vigil, but {PRONOUN/r_c/subject} {VERB/r_c/don't/doesn't} care that m_c is dead. {PRONOUN/r_c/subject/CAP} {VERB/r_c/don't/doesn't} know if {PRONOUN/r_c/subject} ever loved {PRONOUN/m_c/object}, not like {PRONOUN/r_c/subject} {VERB/r_c/were/was} supposed to.",
```

2024-09-24 23:38 UTC, scribblecrumb commented on resources/dicts/events/death/death_reactions/parent/parent_jealousy.json
> +            "r_c keeps up appearances, soothing the fur of {PRONOUN/r_c/poss} dead kit and sitting vigil, but {PRONOUN/r_c/subject} {VERB/r_c/don't/doesn't} care that m_c is dead. {PRONOUN/r_c/subjec
```suggestion
            "r_c keeps up appearances, smoothing the fur of {PRONOUN/r_c/poss} dead kit and sitting vigil, but {PRONOUN/r_c/subject} {VERB/r_c/don't/doesn't} care that m_c is dead. {PRONOUN/r_c/subject/CAP} {VERB/r_c/don't/doesn't} know if {PRONOUN/r_c/subject} ever loved {PRONOUN/m_c/object}, not like {PRONOUN/r_c/subject} {VERB/r_c/were/was} supposed to.",
```

2024-09-25 12:00 UTC, j-gynn commented on resources/dicts/events/death/mountainous.json
> +        "event_text": "m_c sneaks out of camp but finds {PRONOUN/m_c/self} lost in the strange, angular tunnels that lead out into the territory. The Clan search for {PRONOUN/m_c/object} in the morni
Ack this is another British English problem that I wasn't aware was a difference at the time! Though I still maintain y'all are wrong... 😉

2024-09-25 13:02 UTC, scribblecrumb approved these changes

2024-09-25 13:02 UTC, merged