Apprentice Dark forest thought fixes
ClanGenOfficial/clangen pull request #2753
Opened 2024-09-25 22:45 UTC by j-gynn

## About The Pull Request

The Great Pronounify. See Scribble, I can be nice to you with tiny littol PRs!

## Why This Is Good For ClanGen

## Linked Issues

## Proof of Testing

## Changelog/Credits

2024-09-25 23:01 UTC, scribblecrumb requested changes

2024-09-25 23:01 UTC, scribblecrumb commented on resources/dicts/thoughts/dead/darkforest/apprentice.json
> +            "Wonders if it is {PRONOUN/m_c/poss} fault or {PRONOUN/m_c/poss} mentor's fault that they ended up here",
```suggestion
            "Wonders if it is {PRONOUN/m_c/poss} fault or {PRONOUN/m_c/poss} mentor's fault that {PRONOUN/m_c/subject} ended up here",
```

2024-09-25 23:41 UTC, keplerstelescope commented on resources/dicts/thoughts/dead/darkforest/apprentice.json
> +            "Wishes {PRONOUN/m_c/subject} finished {PRONOUN/m_c/poss} battle training",
```suggestion
            "Wishes {PRONOUN/m_c/subject}'d finished {PRONOUN/m_c/poss} battle training",
```

2024-09-26 13:20 UTC, scribblecrumb approved these changes

2024-09-26 13:21 UTC, merged