Plains Med Leaffall Pronouns
ClanGenOfficial/clangen pull request #2766
Opened 2024-09-27 02:38 UTC by tobes03

## About The Pull Request

i thought i'd mix it up this time and... naw i'm just joshing. it's the same as the others

2024-09-27 14:54 UTC, tobes03 commented
idk why i mixed up leafbare and newleaf, but i did leafbare in a past PR. ignore the names of the commits lol

2024-09-28 15:30 UTC, scribblecrumb requested changes

2024-09-28 15:30 UTC, scribblecrumb commented on resources/dicts/patrols/mountainous/med/greenleaf.json
> +                "text": "Ragwort brings strength to cats who need it and eases aching joints, but StarClan, it tastes absolutely <i>foul.</i> p_l's pleased with their harvest, but really wishes they
If "their mouth" refers to both the cats, should it be "their mouths"?

2024-09-28 15:38 UTC, tobes03 commented on resources/dicts/patrols/mountainous/med/greenleaf.json
> +                "text": "Ragwort brings strength to cats who need it and eases aching joints, but StarClan, it tastes absolutely <i>foul.</i> p_l's pleased with their harvest, but really wishes they
oh yeah good point, that's make it clearer

2024-09-28 15:56 UTC, scribblecrumb approved these changes

2024-09-28 15:56 UTC, merged