Leader's Den Other Clan Fail Outcomes
ClanGenOfficial/clangen pull request #2812
Opened 2024-09-30 03:24 UTC by tobes03

## About The Pull Request

Plenty of new fail outcomes for engaging with other Clans. I focused on outcomes that were not stat-locked or trait-locked.

## Why This Is Good For ClanGen

lil variation, eh.

2024-09-30 04:09 UTC, tobes03 commented
Couple typos need to be cleared up, don't merge yet

2024-10-01 12:39 UTC, scribblecrumb requested changes
This is such a crazy amount of new outcomes, ur so cool tobes <3

2024-10-01 12:39 UTC, scribblecrumb commented on resources/dicts/events/leader_den/fail/other_clan.json
> +    "event_text": "o_c_n's cats keep their distance from c_n during the Gathering. No matter what tack m_c tries, o_c_n's leader doesn't seem receptive. Perhaps this alliance is weakning for reasons
```suggestion
    "event_text": "o_c_n's cats keep their distance from c_n during the Gathering. No matter what tack m_c tries, o_c_n's leader doesn't seem receptive. Perhaps this alliance is weakening for reasons {PRONOUN/m_c/subject} {VERB/m_c/are/is}n't aware of.",
```

2024-10-01 12:39 UTC, scribblecrumb commented on resources/dicts/events/leader_den/fail/other_clan.json
> +    "rel_change": 2,
```suggestion
    "rel_change": -2,
```

2024-10-01 12:39 UTC, scribblecrumb commented on resources/dicts/events/leader_den/fail/other_clan.json
> +    "rel_change": 2,
```suggestion
    "rel_change": -2,
```

2024-10-01 22:24 UTC, scribblecrumb approved these changes

2024-10-01 22:25 UTC, merged