[CONTENT] One on One Patrol for Warrior and Apprentice
ClanGenOfficial/clangen pull request #2873
Opened 2024-10-09 01:26 UTC by tobes03

## About The Pull Request

Adding a general training patrol for mentors (hypothetically. it could be any warrior) and apprentices. It has a unique outcome for each trait cluster an apprentice might have! There are no generic outcomes. I have made the relationship change intentionally high, because I think an apprentice should bond faster with the cat training them than any regular patrol's relationship increase.

## Why This Is Good For ClanGen

More specific patrols for a warrior and an apprentice training together.

## Proof of Testing

![image](https://github.com/user-attachments/assets/6a1bd1ff-289d-4bbb-ad7a-4a5912f4b412)
![image](https://github.com/user-attachments/assets/5e57e843-5720-4c98-bb19-56f7d873fa54)
![image](https://github.com/user-attachments/assets/9d635637-c5bb-4360-8e60-56839f5b304b)
![image](https://github.com/user-attachments/assets/ca33f3fd-ae02-44c0-ae7e-ee4d2fb08b23)

2024-10-09 01:48 UTC, scribblecrumb requested changes

2024-10-09 01:48 UTC, scribblecrumb commented on resources/dicts/patrols/general/training.json
> +                "stat_trait": ["troublesome", "rebellious", "cunning", "careful"],
could we add "childish" here? i feel like this can definitely be read in a "overzealous and hyperbolic teen" tone

2024-10-09 01:48 UTC, scribblecrumb commented on resources/dicts/patrols/general/training.json
> +                "stat_trait": [ "insecure", "nervous", "gloomy" ],
ooh this feels like "loving" could also apply! in a "i feel deep love towards my clanmates and want to be able to protect them" way

2024-10-09 01:48 UTC, scribblecrumb commented on resources/dicts/patrols/general/training.json
> +                "stat_trait": [ "righteous", "faithful", "thoughtful", "sincere" ],
perhaps "loving" here as well?

2024-10-09 01:48 UTC, scribblecrumb commented on resources/dicts/patrols/general/training.json
> +                "stat_trait": [ "adventurous" ],
perhaps "lonesome" would also be fitting here? thinking about a future where they're alone.  maybe also "nervous"? a future where they have no one to rely on?

2024-10-09 01:48 UTC, scribblecrumb commented on resources/dicts/patrols/general/training.json
> +                "stat_trait": [ "competitive", "shameless", "flamboyant", "arrogant" ],
perhaps also "ambitious"?

2024-10-09 01:48 UTC, scribblecrumb commented on resources/dicts/patrols/general/training.json
> +                "stat_trait": [ "wise", "thoughtful", "sincere" ],
perhaps also "careful"?

2024-10-09 01:51 UTC, tobes03 commented
Great additions!! I'll stick them in. I esp like the childish one lol. "what if there's a BIG EVIL that we have to BEAT UP" like uh huh uh huh these are directly from your nursery games huh

2024-10-10 00:00 UTC, scribblecrumb approved these changes

2024-10-10 00:00 UTC, merged