[CONTENT] As You Like It-inspired Patrol
ClanGenOfficial/clangen pull request #2900
Opened 2024-10-15 18:52 UTC by tobes03

## About The Pull Request

Another patrol where two cats on a border patrol find two kittypets in an argument.

## Why This Is Good For ClanGen

fun!

## Proof of Testing
![image](https://github.com/user-attachments/assets/ecb9f32d-a7e3-4187-b497-e7441c7849a3)
![image](https://github.com/user-attachments/assets/b9b310f9-8ac8-4991-8b7d-0756a0b3405e)
![image](https://github.com/user-attachments/assets/315d2d78-b03a-4c89-9854-a5350e1c96ac)
![image](https://github.com/user-attachments/assets/e3f61b26-f15c-4c4e-9562-f4ad4648f666)

2024-10-16 00:38 UTC, scribblecrumb requested changes
loving this!  I think it might also be fun to add the "exists" tag to the new cats.  I like the idea of linking two cats that the player might already be aware of.

2024-10-16 00:38 UTC, scribblecrumb commented on resources/dicts/patrols/general/border.json
> +            "text": "p_l doesn't care about kittypet drama. {PRONOUN/p_l/subject/CAP} {VERB/p_l/interrupt/interrupts} and {VERB/p_l/tell/tells} the kittypets to get lost. One kittypet doesn't appreci
```suggestion
            "text": "p_l doesn't care about kittypet drama. {PRONOUN/p_l/subject/CAP} {VERB/p_l/interrupt/interrupts} and {VERB/p_l/tell/tells} the kittypets to get lost. One kittypet doesn't appreciate p_l's tone and takes a swipe at {PRONOUN/p_l/object}. r_c jumps in to help a humiliated p_l drive off the kittypets.",

```

2024-10-16 00:40 UTC, tobes03 commented
ooh fun!! I wasn't really sure how the "exists" tag worked but if it'd be okay here that would be great. I'll add it :)

2024-10-16 00:43 UTC, scribblecrumb commented
It should work here!  It'll only trigger if there's existing cats of the correct status and age

2024-11-16 21:08 UTC, scribblecrumb approved these changes

2024-11-16 21:08 UTC, merged