Content: White + tortie patches
ClanGenOfficial/clangen pull request #2914
Opened 2024-10-20 07:32 UTC by starfelis

- added 2 new tortie patches (CUPID, PEPE)
- added 6 new white patches (BADGER, DORSAL, JUNO, QTIP, MISTLEPAW, POOKIE)

I have checked that they all generate correctly
![dorsal](https://github.com/user-attachments/assets/ffc2f01f-7820-4b3c-97c9-9be82d71bd7f) ![image](https://github.com/user-attachments/assets/c7372497-0eea-4f5a-a0e3-339da45d4a2b) ![image](https://github.com/user-attachments/assets/b02eafaf-fbf3-4476-bde4-6bf99f4d47b3) ![image](https://github.com/user-attachments/assets/17e5ac86-a794-4e64-ae27-3cb29390e7f7)

2024-10-20 11:23 UTC, anjubatus commented
Hello, could you post example pictures of all of them with names in order?

2024-10-20 12:53 UTC, starfelis commented
Cupid | Pepe
![CUPID](https://github.com/user-attachments/assets/5df1fb9f-afe9-4c20-b8ba-22268fed8a41) ![PEPE](https://github.com/user-attachments/assets/39a3cd74-2ffb-4a8a-ae7c-13421ca2da71)
Badger | Dorsal | Juno
![BADGER](https://github.com/user-attachments/assets/397fcae1-cd74-424b-ab9a-5272f154b962) ![DORSAL](https://github.com/user-attachments/assets/9db45fa1-a476-4cee-a6bd-0a4a8b7017c4) ![JUNO](https://github.com/user-attachments/assets/c46afe2e-a595-4da0-9740-2ab4a128d01f)
Qtip | Mistlepaw | Pookie
![QTIP](https://github.com/user-attachments/assets/f42d8f9e-854b-4d98-9595-e4a5390fc155) ![MISTLEPAW](https://github.com/user-attachments/assets/a96fd40c-b543-4217-ab45-122ad0fc426f) ![POOKIE](https://github.com/user-attachments/assets/af4ec670-8954-40be-a47e-2f6853f5607d)

2024-10-23 06:49 UTC, anjubatus requested changes
Thank you!
The torties are very nice. I think that Juno, Qtip and Pookie may be too similar to the tuxedo-like white patches we already have, and since we atm try to limit how many white patches we add to the game, it's probably better to not add those the game, sorry. I also think the badger patch is *too* obviously based on another animal which would throw off people.

If you cut this PR down to Cupid, Pepe, Dorsal and Mistlepaw, we can approve it.

2024-12-20 11:37 UTC, Lixxis commented
@starfelis A small reminder, that some white and tortie patches are approved. Just look at the comment from @anjubatus above, if you want to have the patches added.

2025-03-25 01:14 UTC, scribblecrumb commented
I'm going to close this as stale.  Please refer above, Starfelis, for feedback from Anju!  Feel free to make another PR after applying those changes.

2025-03-25 01:14 UTC, closed without merging