[BUGFIX] TGP: Beach Med Leaf-Bare (Part 3)
ClanGenOfficial/clangen pull request #2933
Opened 2024-10-22 03:25 UTC by LaurBee

## About The Pull Request
Finished pronounifying the Beach Med Leaf-Bare patrol file. Changes include:
- General text edits for grammar/better flow
- Pronoun/Verb tagging
- Adding more scars to outcomes
- Made stat outcomes more common
- Added a few new outcomes to some patrols

## Changelog/Credits
Patrol edits

2024-10-22 14:04 UTC, arisaema12 commented on resources/dicts/patrols/beach/med/leaf-bare.json
> +                "text": "p_l can't say it's <i>fun,</i> swiping away snow to scrounge for the stems and roots of wilted dandelions below, but what matters currently is that it's <i>possible.</i> {PRO
```suggestion
                "text": "p_l can't say it's <i>fun,</i> swiping away snow to scrounge for the stems and roots of wilted dandelions below, but what matters currently is that it's <i>possible.</i> {PRONOUN/p_l/subject/CAP} specifically {VERB/p_l/ensure/ensures}  that, when {PRONOUN/p_l/subject} {VERB/p_l/return/returns} to camp with the additions to the herb stores, the whole camp sees {PRONOUN/p_l/object} praising {PRONOUN/p_l/poss} long-suffering patrol to the leader.",
```

2024-10-30 16:49 UTC, scribblecrumb requested changes

2024-10-30 16:49 UTC, scribblecrumb commented on resources/dicts/patrols/beach/med/leaf-bare.json
> +                "text": "Not only does the duo end up soaked to the skin, they can't even find any dandelions under the snow. app1's left so exhausted that {PRONOUN/app1/subject} {VERB/app1/collapse/
Is this meant to end with ... or with a single period?

2024-10-31 21:18 UTC, LaurBee commented on resources/dicts/patrols/beach/med/leaf-bare.json
> +                "text": "Not only does the duo end up soaked to the skin, they can't even find any dandelions under the snow. app1's left so exhausted that {PRONOUN/app1/subject} {VERB/app1/collapse/
Whoops, must've missed that 😅 Single period. I'm away from my computer rn, but I'll get it fixed ASAP

2024-11-03 02:19 UTC, scribblecrumb approved these changes

2024-11-03 02:19 UTC, merged