[CONTENT] Leader deputy patrols
ClanGenOfficial/clangen pull request #2985
Opened 2024-11-07 20:56 UTC by j-gynn

## About The Pull Request

Adds two new training patrols, both for a 2 cat, leader and deputy situation. One is platonic, one is romantic. I personally send my leader and deputy together a lot and I think it's a bit of missed coverage that there's nothing specific to them. Every outcome has art attached & I have attempted to use the relationship log (development bug ticket incoming!).

## Why This Is Good For ClanGen

More patrols are betterer!

## Proof of Testing
![image](https://github.com/user-attachments/assets/ff3c371e-5981-4f2a-a69f-732b347043b9)
![image](https://github.com/user-attachments/assets/ab2308e4-85f5-4f29-8301-50bce0bb5c91)

## Changelog/Credits
Two new leader-deputy patrols.

2024-11-10 20:49 UTC, scribblecrumb commented
It looks like a lot of other miscellaneous changes were made to other patrols, were any outcomes/patrols removed? And if so, the reasoning?

2024-11-10 20:51 UTC, j-gynn commented
Ugh. my autoformatter strikes again. As far as I'm aware, these should all be whitespace related - no content changes.

2024-11-23 23:27 UTC, scribblecrumb requested changes

2024-11-23 23:27 UTC, scribblecrumb commented on resources/dicts/patrols/general/training.json
> +                            "Had a good patrol with {PRONOUN/m_c/poss} deputy",
My dear friend, ur missing periods on all these logs

2024-12-20 16:51 UTC, selkirks requested changes

2024-12-20 16:51 UTC, selkirks commented on resources/dicts/patrols/general/training.json
> +                        "log": "m_c had a great play-fighting session with r_c when they were out on patrol together"
Missing period at the end of this log

2024-12-20 16:51 UTC, selkirks commented on resources/dicts/patrols/general/training.json
> +                "text": "Both r_c and p_l are positively bursting with things to discuss. Unfortunately, neither is particularly in the mood to sympathise with the other nor help solve their problems
"sympathise" should be "sympathize"

2024-12-20 16:51 UTC, selkirks commented on resources/dicts/patrols/general/training.json
> +                "text": "p_l is halfway through laying out the background of a particularly thorny problem when they are interrupted by another Clanmate springing through the undergrowth towards them
Most of this text needs to be pronoun tagged

2024-12-20 16:51 UTC, selkirks commented on resources/dicts/patrols/general/training.json
> +                        "log": "m_c feels like {PRONOUN/m_c/subject} was completely ignored when {PRONOUN/m_c/subject} tried to talk about important events with r_c on patrol."
'was' should be verb tagged

2024-12-20 16:51 UTC, selkirks commented on resources/dicts/patrols/general/training.json
> +                            "Spent some time sunning with {PRONOUN/m_c/poss} mate r_c while on patrol",
log needs period

2024-12-20 16:51 UTC, selkirks commented on resources/dicts/patrols/general/training.json
> +                            "Spent some time sunning with {PRONOUN/m_c/poss} mate r_c while on patrol"
log needs period

2024-12-20 16:51 UTC, selkirks commented on resources/dicts/patrols/general/training.json
> +        "patrol_id": "gen_train_leaderdeputy_romance_1",
patrol needs a "relationship_constraint": ["mates"],

2024-12-23 23:07 UTC, selkirks requested changes

2024-12-23 23:07 UTC, selkirks commented on resources/dicts/patrols/general/training.json
> -        "weight": 40,
I'm assuming these blocks aren't actually changed and just Github funkiness, right?

2024-12-23 23:07 UTC, selkirks commented on resources/dicts/patrols/general/training.json
> +                        "log": "m_c was impressed by r_c's resourceful solutions to Clanmates' problems that were discussed while out on patrol"
missing period

2024-12-23 23:07 UTC, selkirks commented on resources/dicts/patrols/general/training.json
> +                        "log": "m_c was grateful for r_c's support when {PRONOUN/r_c/subject} allowed {PRONOUN/m_c/object} to vent"
missing period

2025-06-20 01:17 UTC, closed without merging