Resolve inconsistencies in clan_cats.json
ClanGenOfficial/clangen pull request #3059
Opened 2024-11-29 16:37 UTC by rustykitty

## About The Pull Request
1. Tints use `null` instead of `"none"` to indicate no tint.
2. Facets can be null and facets will be regenerated.
3. `pattern` (and `cat.pelt.pattern`) renamed to `tortie_marking` (`cat.pelt.tortiemarking`)

I haven't yet done one of the items requested in #3039, because I'm not too sure how it works. I'll still try a couple things.

## Linked Issues
Fixes #3039

## Proof of Testing
I loaded up one of my medium-size Clans from stable (v0.11.2). Unless otherwise stated, first screenshot is before saving clan and second screenshot is after saving clan.

`null` instead of `none` to indicate no tint:
<img width="759" alt="Screenshot 2024-11-29 at 8 26 44 AM" src="https://github.com/user-attachments/assets/d603036e-74e1-4d79-920f-7239a58f6ff7">
<img width="647" alt="Screenshot 2024-11-29 at 8 28 38 AM" src="https://github.com/user-attachments/assets/fcb56af8-91ca-474f-a74f-0f7254838125">

Allowing facets to be `null`:
<img width="632" alt="Screenshot 2024-11-26 at 9 02 04 PM" src="https://github.com/user-attachments/assets/a2823c86-b254-4cd6-b371-71f65aaa2ebd">
<img width="632" alt="Screenshot 2024-11-26 at 9 02 11 PM" src="https://github.com/user-attachments/assets/3a1cf101-18f0-455c-b18c-959c8a6dfde8">

Pattern renamed to tortie marking:
<img width="632" alt="image" src="https://github.com/user-attachments/assets/cc10b8aa-0e87-4c54-9df8-b34fe2a4bd78">
<img width="644" alt="image" src="https://github.com/user-attachments/assets/45ff5080-34ae-4b32-9ad7-5eabae5635a9">

## Changelog/Credits

2025-01-13 04:22 UTC, j-gynn requested changes
Two little things (sorry for the delay on getting this reviewed!).

2025-01-13 04:22 UTC, j-gynn commented on scripts/clan.py
> +            if general[3] == None or general[3] == "None":
```suggestion
            if general[3] is None or general[3] == "None":
```
It's more Pythonic to say `if [variable] is None`, or alternatively, `if not [variable]`. Please make this change wherever relevant

2025-01-13 04:22 UTC, j-gynn commented on scripts/cat/pelts.py
> +        elif self.white_patches in ['SEPIAPOINT', 'MINKPOINT', 'SEALPOINT']:
This is so hilariously minor but since I've asked for other changes, could these single quotes be replaced with double quotes?

2025-03-06 23:08 UTC, j-gynn requested changes
Could you please test these changes with a `.txt` Clan? I believe some of these changes may break how they load (there should be one posted recently in the developer section of the Discord as of this message being sent).

2025-03-06 23:08 UTC, j-gynn commented on scripts/clan.py
> +            elif general[7] is None:
Since these are actually checking against the strings loaded from the `.txt` file, I'm not confident this change actually works as intended?

2025-03-06 23:08 UTC, j-gynn commented on scripts/clan.py
> +            elif general[3] is None:
same concern about `.txt` file loading.

2025-03-06 23:11 UTC, j-gynn requested changes, later dismissed
[oops internet got angy, double-post]

2025-03-08 16:03 UTC, rustykitty commented on scripts/clan.py
> +            elif general[7] is None:
Looking at this, you may actually be right. I didn't notice it was in the `txt` function!

2025-07-26 01:49 UTC, scribblecrumb requested changes
Just one little thing!

2025-07-26 01:49 UTC, scribblecrumb commented on scripts/game_structure/load_cat.py
> +            # - white patches(19) - pattern(20) - tortie_base(21) - tortie_pattern(22) - tortie_colour(23) - skin(24) - skill(25) - NONE(26) - spec(27) - accessory(28) -
revert these changes I think, we want this comment to stay consistent with how the csv saves looked way back when lol

2025-08-12 20:57 UTC, scribblecrumb approved these changes

2025-08-12 20:58 UTC, merged