Cat hover sprites correctly on Clan screen
ClanGenOfficial/clangen pull request #3101
Opened 2024-12-02 21:07 UTC by j-gynn

## About The Pull Request
Improves the Clan screen cat sprites in several ways (more to come).

- Cats layer correctly, so if you click an orange goof, you won't get the brown derp in front.
- Speaking of, the clickable area is now cat-shaped, so you can actually click on a cat that's behind another. Mileage may vary as there's a bit of a buffer around them to make it easier to click.
- Tooltips! Now, when you hover over a cat on this screen, you'll see their name in a cute little tooltip. Just helps you identify your kitties \*and\* know you're clicking on Brightpaw rather than Comfreynose.

## Why This Is Good For ClanGen
Improvements to Clan screen good.

## Proof of Testing
![image](https://github.com/user-attachments/assets/cddec641-14ad-4616-9ae9-214fbfd77377)
![image](https://github.com/user-attachments/assets/2327ff3c-8293-4313-8fa2-099f22e95bfb)

## Changelog/Credits

2024-12-02 21:11 UTC, j-gynn commented
\*my goddamn linter holy shirt.\* sorry senior devs, I am once again on my whitespace bullshit

2024-12-04 01:13 UTC, scribblecrumb requested changes

2024-12-04 01:13 UTC, scribblecrumb commented on resources/dicts/backstories.json
begging you to undo this one

2024-12-04 01:13 UTC, scribblecrumb commented on scripts/cat/pelts.py
can we undo this one too please?

2024-12-05 15:59 UTC, j-gynn commented on scripts/cat/pelts.py
Not easily, as there's work that's been done here that's needed for the PR, I think. What exactly do we not like about what the linter has done?

2024-12-06 02:32 UTC, j-gynn commented
Hold off on this one for now, we've discovered a potentially-seizure inducing bug. Investigating...!

2024-12-06 08:52 UTC, j-gynn commented
Fixed the concerning strobe!

2024-12-11 02:23 UTC, scribblecrumb commented on resources/credits_text.json
were these changes intentional?

2024-12-11 02:23 UTC, scribblecrumb commented on resources/dicts/events/misc/general.json
>    },
this event got doubled for some reason?

2024-12-12 22:27 UTC, j-gynn commented on resources/credits_text.json
Done as part of updating the credits to match the google sheets file iirc... not sure why that's in this branch and not the credits revamp one. Happy to revert these if you like!

2024-12-13 00:26 UTC, scribblecrumb commented on resources/credits_text.json
Yeah let's revert just to keep things organized.

2024-12-14 01:52 UTC, j-gynn commented on resources/credits_text.json
Just checked it now and these so-called changes are actually in parity with development and not changes. Weird.

2024-12-14 01:52 UTC, j-gynn commented on resources/dicts/events/misc/general.json
>    },
Oops. That's been yeeted now

2024-12-23 15:12 UTC, scribblecrumb commented
Ugh, I keep forgetting to look at this.  Resolve the conflicts and I'll get it approved (totally feel free to DM me so i don't miss it again)

2024-12-30 17:51 UTC, j-gynn commented
Removed the tool_tip feature from this PR unfortunately as it's causing so many problems. Leaving the base code for it so people could use it in future (the issue here is with overlapping rects blocking the new tooltip from displaying and I can't for the life of me figure out why. Otherwise, ready for review!

2025-03-25 01:19 UTC, scribblecrumb approved these changes
Approved, just resolve the conflicts before merging <3

2025-06-20 03:06 UTC, merged