Fix ProfileScreen UIWindow bug and debug menu layering issue.
ClanGenOfficial/clangen pull request #3183
Opened 2024-12-15 21:01 UTC by Treefire33

## About The Pull Request
Prevents the use of keybinds when a window is open on ProfileScreen.
Forces the debug menu to always be on top.

## Linked Issues
fixes: #3178
fixes: #3179

## Proof of Testing

https://github.com/user-attachments/assets/6d47248a-4318-4ca4-835b-50ebd8a2a5c0
(Key 27 is Escape)

2024-12-15 23:33 UTC, j-gynn requested changes
Would it be possible to get pressing ESC to close those windows rather than doing nothing? I have a hatred (/lh) of the `window_open` variable and killed it in the fullscreen rework, so I'd really, really love it if it could continue to Not Exist 😂

2024-12-16 01:19 UTC, scribblecrumb commented
Additionally, if these issues exist on the stable version, then lets get this targeted at the 0.12.0 branch.

2024-12-16 01:23 UTC, j-gynn commented
Ah - I think the new debug is a development feature, but I don't know about the other bug. If that's present in `release 0.12.0`, we might want to split this into 2 PRs - one targeting release, one targeting development. Annoying, I know.

2024-12-21 23:45 UTC, j-gynn requested changes, later dismissed
Last thing, I promise! We need to only allow ESC if keybinds are enabled.

2024-12-21 23:45 UTC, j-gynn commented on scripts/game_structure/windows.py
> +        elif event.type == pygame.KEYDOWN and event.key == pygame.K_ESCAPE:
Also need to check that the user has keybinds enabled (I think it's `game.settings["keybinds"]` but do double-check that).

2025-01-07 21:29 UTC, j-gynn commented on scripts/game_structure/windows.py
> +            game.all_screens["profile screen"].exit_screen()
Don't exit the background screen, just close the menu. In other words, if you have this menu open and press ESC, close this menu *and nothing else*. Sorry I haven't been super clear on that 😅

2025-06-15 14:59 UTC, scribblecrumb approved these changes

2025-06-15 14:59 UTC, merged