Replaces non-existent traits
ClanGenOfficial/clangen pull request #3185
Opened 2024-12-16 21:25 UTC by arisaema12

## About The Pull Request
Replaces some non-existent traits with ones currently in use, so that these relationship events can appear in-game again.

## Proof of Testing
I only replaced some traits, I swear nothing's broken

## Changelog/Credits
- Replaces non-existent traits with existing ones

2024-12-17 15:04 UTC, j-gynn requested changes
Please can these changes be made from `release-0.12.0` and targeted there, as I think they affect stable too.

2024-12-18 05:02 UTC, scribblecrumb approved these changes

2024-12-18 05:02 UTC, scribblecrumb requested changes
wait oops didn't see gynn's comment lmaoo, approval revoked

2024-12-19 18:34 UTC, arisaema12 commented
Sorry I'm not really sure how to do this and don't want to accidentally explode something, so I'm going to close this pull request and open a new one for the correct release instead

2024-12-19 18:34 UTC, closed without merging