[BUGFIX] Correct patrols that give background
ClanGenOfficial/clangen pull request #3204
Opened 2024-12-19 14:49 UTC by rustykitty

## About The Pull Request
Fixes the patrol attributes so that backstories/events with new cats work correctly.
Specifically, I code to actually pull a random backstory when we override it, then I noticed that some events' backstory attributes separated backstories by a comma and space instead of just a comma, so I added that in as well.

## Why This Is Good For ClanGen

## Linked Issues
Fixes #3180, #3200, #3203

## Proof of Testing
<img width="912" alt="Screenshot 2024-12-19 at 6 38 10 AM" src="https://github.com/user-attachments/assets/70513481-7552-4ed4-b87a-b2253dcc4aeb" />
<img width="912" alt="Screenshot 2024-12-19 at 6 38 00 AM" src="https://github.com/user-attachments/assets/7b98a172-ee6c-480a-8d63-d37d5aaaa891" />

## Changelog/Credits
Cats found on patrol or in event now have backstories assigned correctly

2024-12-20 05:24 UTC, scribblecrumb commented
This should be aimed at the 0.12.0 branch

2024-12-21 23:49 UTC, j-gynn commented on scripts/screens/MakeClanScreen.py
Why is this change in this PR? I think it ought to be in `release-0.12.0` anyway, but...

2024-12-21 23:49 UTC, j-gynn requested changes, later dismissed
One change seems like it doesn't belong in this PR?

2024-12-22 00:15 UTC, rustykitty commented on scripts/screens/MakeClanScreen.py
oops, I might have rebased incorrectly

2024-12-22 00:17 UTC, rustykitty commented on scripts/screens/MakeClanScreen.py
should be fixed now
<img width="163" alt="image" src="https://github.com/user-attachments/assets/b88e8cb2-52e1-485b-a6e3-662de9a32987" />

2024-12-23 15:20 UTC, scribblecrumb approved these changes

2024-12-23 15:21 UTC, merged