[CLEANUP] Prune outdated patrols
ClanGenOfficial/clangen pull request #3245
Opened 2024-12-24 05:17 UTC by SunlitFable

## About The Pull Request
Delete all patrols in the Wetlands and Desert folders that are non-unique

## Why This Is Good For ClanGen

The removed patrols are not up to current standards, and they bog down patrol work. Removal ensures that all content is high-quality and properly tested

## Linked Issues
[Discussed in senior chat.](https://discord.com/channels/1003759225522110524/1027297667623174207/1320853116186394655)

## Proof of Testing
![Illustration2](https://github.com/user-attachments/assets/a8f7129f-9538-4323-afb6-0911575df783)

## Changelog/Credits
Prune outdated patrols in Wetlands and Desert

2024-12-25 22:50 UTC, j-gynn commented
uhhh that's one heck of a merge conflict @SunlitFable

2024-12-25 22:53 UTC, SunlitFable commented
> uhhh that's one heck of a merge conflict @SunlitFable

what the heck 😭 I'll fix in a bit, it was fine when I checked last

2024-12-30 00:28 UTC, Tiritirimatangi requested changes
Okay I finally know what scribble feels every time I turn up with a huge PR XD

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/hunting/any.json
> -        "patrol_id": "dst_gen_hunt_twolegplace1",
keep this one - it's unique to the desert. Possibly throw it up in the discord for a rewrite/additional outcomes though?

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/hunting/any.json
> -        "patrol_id": "dst_gen_hunt_twolegplace2",
same with this

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/hunting/any.json
> -        "patrol_id": "dst_hunt_solo2",
keeep this one but ask discord for more outcomes?

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/hunting/any.json
> -        "patrol_id": "dst_hunt_solo3",
keep but modify?

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/hunting/any.json
> -        "patrol_id": "dst_hunt_solo4",
keep but modify?

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/hunting/any.json
> -        "patrol_id": "dst_hunt_swiftfox_anysteal1",
unique to the desert, pls keep

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/hunting/any.json
> -        "patrol_id": "dst_hunt_swiftfox_anysteal2",
unique to desert, pls keep

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/hunting/any.json
> -        "patrol_id": "dst_hunt_kitfox_scavenge1",
unique to desert pls keep

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/hunting/any.json
> -        "patrol_id": "dst_hunt_kitfox_scavenge2",
unique to desert pls keep

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/hunting/any.json
> -        "patrol_id": "dst_hunt_kitfox_scavenge3",
unique to desert pls keep

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/hunting/any.json
> -        "patrol_id": "dst_hunt_kitfox_steal1",
unique to desert pls keep (desert cats eat the bloody fox lol)

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/hunting/any.json
> -        "patrol_id": "dst_hunt_kitfox_steal2",
unique to desert, pls keep

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/hunting/any.json
> -        "patrol_id": "dst_hunt_kitfox_steal3",
unique to desert, pls keep

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/hunting/greenleaf.json
> -    {
unique to desert, pls keep

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/hunting/greenleaf.json
> -        "patrol_id": "dst_hunt_heat1",
unique to desert, pls keep

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/hunting/leaf-bare.json
> -        "patrol_id": "dst_hunt_herb_warriorleafbare1",
unique to desert, pls keep

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/hunting/leaf-bare.json
> -        "patrol_id": "dst_hunt_leafbarerainstorm1",
unique to desert, pls keep

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/hunting/leaf-bare.json
> -        "patrol_id": "dst_hunt_leafbarerainstorm2",
unique to desert, pls keep

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/hunting/leaf-bare.json
> -        "patrol_id": "dst_hunt_leafbarerainstorm3",
this one should probably be rewritten

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/hunting/leaf-bare.json
> -        "patrol_id": "dst_hunt_swiftfox_leaf-barevixen1",
unique to desert, pls keep

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/hunting/leaf-bare.json
> -    {
unique to desert, pls keep

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/hunting/leaf-fall.json
> -        "patrol_id": "dst_hunt_heat5",
unique to desert, pls keep

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/hunting/leaf-fall.json
> -        "patrol_id": "dst_hunt_heat6",
unique to desert, pls keep

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/hunting/leaf-fall.json
> -        "patrol_id": "dst_hunt_swiftfox_leaf-fallvixen1",
unique to desert, pls keep

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/hunting/leaf-fall.json
> -        "patrol_id": "dst_hunt_swiftfox_leaf-fallvixen1",
however, either needs to be made into border patrol or given a prey reward, desert cats will eat swift fows if they can?

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/hunting/leaf-fall.json
> -        "patrol_id": "dst_hunt_swiftfox_leaf-fallvixen2",
unique to desert, keep and turn into border patrol

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/hunting/newleaf.json
> -    {
unique to desert, keep and turn into border patrol

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/hunting/newleaf.json
> -    {
unique to desert, pls keep

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/hunting/newleaf.json
> -        "patrol_id": "dst_hunt_heat4",
unique to desert, pls keep

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/hunting/newleaf.json
> -        "patrol_id": "dst_hunt_swiftfox_newleafvixen1",
unique to desert, pls keep and turn into border patrol

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/med/leaf-bare.json
> -        "patrol_id": "dst_med_leafbare_daisy_lorestoryhealinglocked1",
unique to desert, pls keep

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/training/any.json
> -        "patrol_id": "dst_train_session1",
unique to desert, pls keep

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/training/any.json
> -        "patrol_id": "dst_train_soloapp1",
might need rewriting if me want to keep it

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/training/any.json
> -        "patrol_id": "dst_train_oasisswim1",
unique to desert, pls keep

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/training/any.json
> -        "patrol_id": "dst_train_glowingscorpians1",
unique to desert, pls keep

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/training/any.json
> -        "patrol_id": "dst_train_throwsand1",
what the fuck was I doing here

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/training/any.json
> -        "patrol_id": "dst_train_arguingromance1",
unique to desert, pls keep

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/training/leaf-bare.json
> -        "patrol_id": "dst_train_leafbare_beetlesoloapp1",
not unique to desert, but unique to only some biomes. pls keep?

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/desert/med/any.json
> -        "patrol_id": "dst_medcat_emergency1",
keep but move to appropriate file?

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/wetlands/hunting/any.json
> -        "patrol_id": "wtlnd_hunt_lilsalamander1",
unique to wetlands, pls keep

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/wetlands/hunting/any.json
> -
not unique to wetlands, pls keep anyway due to only being appropriate for wetlands and beach

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/wetlands/hunting/any.json
> -
same here

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/wetlands/hunting/greenleaf.json
> -        "patrol_id": "wtlnd_hunt_redvixen13",
keep but make border patrol

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/wetlands/hunting/greenleaf.json
> -        "patrol_id": "wtlnd_hunt_redvixen14",
keep but make border patrol

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/wetlands/hunting/greenleaf.json
> -        "patrol_id": "wtlnd_hunt_redvixen6",
keep but make border patrol

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/wetlands/hunting/greenleaf.json
> -        "patrol_id": "wtlnd_hunt_grayvixen4",
keep but make border patrol

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/wetlands/hunting/greenleaf.json
> -        "patrol_id": "wtlnd_hunt_grayvixen5",
keep but make border patrol

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/wetlands/hunting/greenleaf.json
> -        "patrol_id": "wtlnd_hunt_grayvixen15",
keep but make border patrol

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/wetlands/hunting/greenleaf.json
> -        "patrol_id": "wtlnd_hunt_swiftfox_greenleafscavenge3",
pls keep

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/wetlands/hunting/greenleaf.json
> -        "patrol_id": "wtlnd_hunt_redvixen4",
keep but make border patrol

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/wetlands/hunting/greenleaf.json
> -        "patrol_id": "wtlnd_hunt_redvixen5",
keep but make border patrol

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/wetlands/hunting/greenleaf.json
> -        "patrol_id": "wtlnd_hunt_redvixen15",
keep but make border patrol

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/wetlands/hunting/greenleaf.json
> -        "patrol_id": "wtlnd_hunt_heat1",
unique to wetlands, pls keep

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/wetlands/hunting/leaf-bare.json
> -        "patrol_id": "wtlnd_hunt_kitfox_scavenge1",
keep but make into border patrol

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/wetlands/hunting/leaf-bare.json
> -    {
keep but make into a border patrol

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/wetlands/hunting/leaf-bare.json
> -        "patrol_id": "wtlnd_hunt_leafbare_kingfisher_storylorehunterclimberteacherlocked1",
unique to wetlands, pls keep

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/wetlands/hunting/leaf-fall.json
> -        "patrol_id": "wtlnd_hunt_redvixen7",
keep but make into border patrol

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/wetlands/hunting/leaf-fall.json
> -        "patrol_id": "wtlnd_hunt_grayvixen16",
keep but make into border patrol

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/wetlands/hunting/leaf-fall.json
> -        "patrol_id": "wtlnd_hunt_grayvixen17",
keep but make into border patrol

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/wetlands/hunting/leaf-fall.json
> -        "patrol_id": "wtlnd_hunt_redvixen17",
keep but make into border patrol

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/wetlands/hunting/leaf-fall.json
> -        "patrol_id": "wtlnd_hunt_grayvixen18",
keep but make border?

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/wetlands/hunting/newleaf.json
> -        "patrol_id": "wtlnd_hunt_redvixen1",
keep but make border?

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/wetlands/hunting/newleaf.json
> -        "patrol_id": "wtlnd_hunt_redvixen2",
keep but make border?

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/wetlands/hunting/newleaf.json
> -        "patrol_id": "wtlnd_hunt_grayvixen1",
keep but make border?

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/wetlands/hunting/newleaf.json
> -        "patrol_id": "wtlnd_hunt_grayvixen2",
keep but make border?

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/wetlands/hunting/newleaf.json
> -        "patrol_id": "wtlnd_hunt_redvixen11",
keep but make border?

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/wetlands/hunting/newleaf.json
> -        "patrol_id": "wtlnd_hunt_grayvixen10",
keep but make border?

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/wetlands/training/any.json
> -        "patrol_id": "wtl_any_train_session1",
unique to wetlands, pls keep

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/wetlands/training/any.json
> -        "patrol_id": "wtlnd_train_fireflies",
unique to wetlands, pls keep

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/wetlands/training/any.json
> -        "patrol_id": "wtlnd_train_arguingromance1",
unique to wetlands, pls keep

2024-12-30 00:28 UTC, Tiritirimatangi commented on resources/lang/en/patrols/wetlands/training/any.json
> -        "patrol_id": "wtlnd_train_any_beetlesoloapp1",
not unique to wetlands but pls keep anyway

2024-12-30 21:50 UTC, SunlitFable commented on resources/lang/en/patrols/desert/training/any.json
> -        "patrol_id": "dst_train_throwsand1",
i have no idea LMFAO

2025-01-01 04:07 UTC, closed without merging

2025-01-01 04:07 UTC, SunlitFable commented
temp closing because my monitor broke and i can't work on this until its fixed </3